// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthHealthGetData, HealthHealthGetErrors, HealthHealthGetResponses, PushMessageApiV1MessagePushPushPostData, PushMessageApiV1MessagePushPushPostErrors, PushMessageApiV1MessagePushPushPostResponses, SubmitFeedbackApiV1MessagePushFeedbackPostData, SubmitFeedbackApiV1MessagePushFeedbackPostErrors, SubmitFeedbackApiV1MessagePushFeedbackPostResponses, TestPushApiV1MessagePushTestPostData, TestPushApiV1MessagePushTestPostErrors, TestPushApiV1MessagePushTestPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * 健康检查
 *
 * 访问返回 204 即代表服务存活且 RabbitMQ broker 连接正常。
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>): RequestResult<HealthHealthGetResponses, HealthHealthGetErrors, ThrowOnError> => (options?.client ?? client).get<HealthHealthGetResponses, HealthHealthGetErrors, ThrowOnError>({ url: '/health', ...options });

/**
 * Push Message
 *
 * 投递一条推送请求到 RabbitMQ，由 message-service 消费者异步分发。
 *
 * 等价于各微服务原先「直接调用 PushMe / PushPlus 接口」的逻辑，
 * 现在统一改为调用本接口，由 message-service 集中推送。
 * 上游透传的 x-bili-* 用户信息由 CurrentUser 依赖解析，
 * 在投递前直接拼进推送标题（标题前缀），便于消费者区分推送来源。
 *
 * 微服务间完全互信，不做令牌校验。
 */
export const pushMessageApiV1MessagePushPushPost = <ThrowOnError extends boolean = false>(options: Options<PushMessageApiV1MessagePushPushPostData, ThrowOnError>): RequestResult<PushMessageApiV1MessagePushPushPostResponses, PushMessageApiV1MessagePushPushPostErrors, ThrowOnError> => (options.client ?? client).post<PushMessageApiV1MessagePushPushPostResponses, PushMessageApiV1MessagePushPushPostErrors, ThrowOnError>({
    url: '/api/v1/message/push/push',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Test Push
 *
 * 立即发送一条测试推送（不经过队列），便于前端 / 用户验证渠道配置。
 */
export const testPushApiV1MessagePushTestPost = <ThrowOnError extends boolean = false>(options: Options<TestPushApiV1MessagePushTestPostData, ThrowOnError>): RequestResult<TestPushApiV1MessagePushTestPostResponses, TestPushApiV1MessagePushTestPostErrors, ThrowOnError> => (options.client ?? client).post<TestPushApiV1MessagePushTestPostResponses, TestPushApiV1MessagePushTestPostErrors, ThrowOnError>({
    url: '/api/v1/message/push/test',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Submit Feedback
 *
 * 前端提交反馈，仅推送到站长自己的推送设置（全局 message_config）。
 *
 * 不接收也不使用调用方传入的 per-user 渠道配置，固定回落到 message-service 的
 * 全局环境变量配置（MESSAGE_CONFIG），确保反馈只发到站长本人。
 * 标题包含来源（source）与用户标签，便于区分反馈来自哪个页面 / 哪位用户。
 *
 * 微服务间完全互信，不做令牌校验。
 */
export const submitFeedbackApiV1MessagePushFeedbackPost = <ThrowOnError extends boolean = false>(options: Options<SubmitFeedbackApiV1MessagePushFeedbackPostData, ThrowOnError>): RequestResult<SubmitFeedbackApiV1MessagePushFeedbackPostResponses, SubmitFeedbackApiV1MessagePushFeedbackPostErrors, ThrowOnError> => (options.client ?? client).post<SubmitFeedbackApiV1MessagePushFeedbackPostResponses, SubmitFeedbackApiV1MessagePushFeedbackPostErrors, ThrowOnError>({
    url: '/api/v1/message/push/feedback',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
