// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:10013' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessageUser
 *
 * 推送发起方的用户信息。
 *
 * 由上游 FastapiApp / RPA-Browser 经 nodejs-pptr 代理通过 x-bili-* 请求头透传，
 * message-service 解析后写入推送内容（标题前缀），便于区分「是谁触发的推送」。
 * 字段与 RPA-Browser / nodejs-pptr ProxyEndPort 中 setUserHeaders 注入的
 * x-bili-* 头一一对应。
 */
export type MessageUser = {
    /**
     * Mid
     */
    mid?: string | null;
    /**
     * User Name
     */
    user_name?: string | null;
    /**
     * Uname
     */
    uname?: string | null;
    /**
     * Level
     */
    level?: string | null;
    /**
     * Role
     */
    role?: string | null;
    /**
     * Sign
     */
    sign?: string | null;
    /**
     * Sex
     */
    sex?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Vip Status
     */
    vip_status?: string | null;
    /**
     * Vip Type
     */
    vip_type?: string | null;
};

/**
 * PushChannelConfig
 *
 * 推送渠道配置模型（消息系统「推送」模块的渠道配置）。
 *
 * 字段与 RPA-Browser / FastapiApp 的 PushChannelConfig 保持一致，以便直接接收
 * 它们序列化后的 per-user 配置。未知字段一律忽略。
 */
export type PushChannelConfig = {
    /**
     * Hitokoto
     */
    hitokoto?: boolean;
    /**
     * Bark Push
     */
    bark_push?: string;
    /**
     * Bark Archive
     */
    bark_archive?: string;
    /**
     * Bark Group
     */
    bark_group?: string;
    /**
     * Bark Sound
     */
    bark_sound?: string;
    /**
     * Bark Icon
     */
    bark_icon?: string;
    /**
     * Bark Level
     */
    bark_level?: string;
    /**
     * Bark Url
     */
    bark_url?: string;
    /**
     * Dd Bot Secret
     */
    dd_bot_secret?: string;
    /**
     * Dd Bot Token
     */
    dd_bot_token?: string;
    /**
     * Fskey
     */
    fskey?: string;
    /**
     * Gobot Url
     */
    gobot_url?: string;
    /**
     * Gobot Qq
     */
    gobot_qq?: string;
    /**
     * Gobot Token
     */
    gobot_token?: string;
    /**
     * Gotify Url
     */
    gotify_url?: string;
    /**
     * Gotify Token
     */
    gotify_token?: string;
    /**
     * Gotify Priority
     */
    gotify_priority?: number;
    /**
     * Igot Push Key
     */
    igot_push_key?: string;
    /**
     * Push Key
     */
    push_key?: string;
    /**
     * Deer Key
     */
    deer_key?: string;
    /**
     * Deer Url
     */
    deer_url?: string;
    /**
     * Chat Url
     */
    chat_url?: string;
    /**
     * Chat Token
     */
    chat_token?: string;
    /**
     * Push Plus Token
     */
    push_plus_token?: string;
    /**
     * Push Plus Url
     */
    push_plus_url?: string;
    /**
     * Push Plus User
     */
    push_plus_user?: string;
    /**
     * Push Plus Template
     */
    push_plus_template?: string;
    /**
     * Push Plus Channel
     */
    push_plus_channel?: string;
    /**
     * Push Plus Webhook
     */
    push_plus_webhook?: string;
    /**
     * Push Plus Callbackurl
     */
    push_plus_callbackurl?: string;
    /**
     * Push Plus To
     */
    push_plus_to?: string;
    /**
     * We Plus Bot Token
     */
    we_plus_bot_token?: string;
    /**
     * We Plus Bot Receiver
     */
    we_plus_bot_receiver?: string;
    /**
     * We Plus Bot Version
     */
    we_plus_bot_version?: string;
    /**
     * Qmsg Key
     */
    qmsg_key?: string;
    /**
     * Qmsg Type
     */
    qmsg_type?: string;
    /**
     * Qywx Origin
     */
    qywx_origin?: string;
    /**
     * Qywx Am
     */
    qywx_am?: string;
    /**
     * Qywx Key
     */
    qywx_key?: string;
    /**
     * Tg Bot Token
     */
    tg_bot_token?: string;
    /**
     * Tg User Id
     */
    tg_user_id?: string;
    /**
     * Tg Api Host
     */
    tg_api_host?: string;
    /**
     * Tg Proxy Auth
     */
    tg_proxy_auth?: string;
    /**
     * Tg Proxy Host
     */
    tg_proxy_host?: string;
    /**
     * Tg Proxy Port
     */
    tg_proxy_port?: string;
    /**
     * Aibotk Key
     */
    aibotk_key?: string;
    /**
     * Aibotk Type
     */
    aibotk_type?: string;
    /**
     * Aibotk Name
     */
    aibotk_name?: string;
    /**
     * Smtp Server
     */
    smtp_server?: string;
    /**
     * Smtp Ssl
     */
    smtp_ssl?: string;
    /**
     * Smtp Email
     */
    smtp_email?: string;
    /**
     * Smtp Password
     */
    smtp_password?: string;
    /**
     * Smtp Name
     */
    smtp_name?: string;
    /**
     * Pushme Key
     */
    pushme_key?: string;
    /**
     * Pushme Url
     */
    pushme_url?: string;
    /**
     * Chronocat Qq
     */
    chronocat_qq?: string;
    /**
     * Chronocat Token
     */
    chronocat_token?: string;
    /**
     * Chronocat Url
     */
    chronocat_url?: string;
    /**
     * Webhook Url
     */
    webhook_url?: string;
    /**
     * Webhook Body
     */
    webhook_body?: string;
    /**
     * Webhook Headers
     */
    webhook_headers?: string;
    /**
     * Webhook Method
     */
    webhook_method?: string;
    /**
     * Webhook Content Type
     */
    webhook_content_type?: string;
    /**
     * Ntfy Url
     */
    ntfy_url?: string;
    /**
     * Ntfy Topic
     */
    ntfy_topic?: string;
    /**
     * Ntfy Priority
     */
    ntfy_priority?: string;
    /**
     * Ntfy Token
     */
    ntfy_token?: string;
    /**
     * Ntfy Username
     */
    ntfy_username?: string;
    /**
     * Ntfy Password
     */
    ntfy_password?: string;
    /**
     * Ntfy Actions
     */
    ntfy_actions?: string;
    /**
     * Wxpusher App Token
     */
    wxpusher_app_token?: string;
    /**
     * Wxpusher Topic Ids
     */
    wxpusher_topic_ids?: string;
    /**
     * Wxpusher Uids
     */
    wxpusher_uids?: string;
};

/**
 * PushMessage
 *
 * 通过消息队列投递的推送请求（消息系统的「推送」模块）。
 *
 * 等价于各微服务原先「直接调用 PushMe / PushPlus 接口」的逻辑，
 * 现在统一改为投递到 message-service，由消费者异步分发。
 */
export type PushMessage = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Push Type
     */
    push_type?: string | null;
    config?: PushChannelConfig | null;
    user?: MessageUser | null;
    /**
     * Requires Login
     */
    requires_login?: boolean;
};

/**
 * StandardResponse
 */
export type StandardResponse = {
    /**
     * Code
     */
    code?: number;
    /**
     * Data
     */
    data?: unknown | null;
    /**
     * Msg
     */
    msg?: string;
};

/**
 * TestPushRequest
 */
export type TestPushRequest = {
    /**
     * Title
     */
    title?: string;
    /**
     * Content
     */
    content?: string;
    /**
     * Push Type
     */
    push_type?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Requires Login
     */
    requires_login?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetErrors = {
    /**
     * broker 未连接
     */
    503: unknown;
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type PushMessageApiV1MessagePushPushPostData = {
    body: PushMessage;
    path?: never;
    query?: never;
    url: '/api/v1/message/push/push';
};

export type PushMessageApiV1MessagePushPushPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PushMessageApiV1MessagePushPushPostError = PushMessageApiV1MessagePushPushPostErrors[keyof PushMessageApiV1MessagePushPushPostErrors];

export type PushMessageApiV1MessagePushPushPostResponses = {
    /**
     * Successful Response
     */
    200: StandardResponse;
};

export type PushMessageApiV1MessagePushPushPostResponse = PushMessageApiV1MessagePushPushPostResponses[keyof PushMessageApiV1MessagePushPushPostResponses];

export type TestPushApiV1MessagePushTestPostData = {
    body: TestPushRequest;
    path?: never;
    query?: never;
    url: '/api/v1/message/push/test';
};

export type TestPushApiV1MessagePushTestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestPushApiV1MessagePushTestPostError = TestPushApiV1MessagePushTestPostErrors[keyof TestPushApiV1MessagePushTestPostErrors];

export type TestPushApiV1MessagePushTestPostResponses = {
    /**
     * Successful Response
     */
    200: StandardResponse;
};

export type TestPushApiV1MessagePushTestPostResponse = TestPushApiV1MessagePushTestPostResponses[keyof TestPushApiV1MessagePushTestPostResponses];
