// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AddIceCandidateApiV1RpaBrowserControlWebrtcIceCandidatePostData, AddIceCandidateApiV1RpaBrowserControlWebrtcIceCandidatePostErrors, AddIceCandidateApiV1RpaBrowserControlWebrtcIceCandidatePostResponses, ClosePageApiV1RpaBrowserControlPagesClosePostData, ClosePageApiV1RpaBrowserControlPagesClosePostErrors, ClosePageApiV1RpaBrowserControlPagesClosePostResponses, CloseWebrtcStreamApiV1RpaBrowserControlWebrtcClosePostData, CloseWebrtcStreamApiV1RpaBrowserControlWebrtcClosePostErrors, CloseWebrtcStreamApiV1RpaBrowserControlWebrtcClosePostResponses, CreateWebrtcOfferApiV1RpaBrowserControlWebrtcOfferPostData, CreateWebrtcOfferApiV1RpaBrowserControlWebrtcOfferPostErrors, CreateWebrtcOfferApiV1RpaBrowserControlWebrtcOfferPostResponses, GetPagesListApiV1RpaBrowserControlPagesListPostData, GetPagesListApiV1RpaBrowserControlPagesListPostErrors, GetPagesListApiV1RpaBrowserControlPagesListPostResponses, GetWebrtcStatusApiV1RpaBrowserControlWebrtcStatusPostData, GetWebrtcStatusApiV1RpaBrowserControlWebrtcStatusPostErrors, GetWebrtcStatusApiV1RpaBrowserControlWebrtcStatusPostResponses, HandleWebrtcAnswerApiV1RpaBrowserControlWebrtcAnswerPostData, HandleWebrtcAnswerApiV1RpaBrowserControlWebrtcAnswerPostErrors, HandleWebrtcAnswerApiV1RpaBrowserControlWebrtcAnswerPostResponses, SwitchPageApiV1RpaBrowserControlPagesSwitchPostData, SwitchPageApiV1RpaBrowserControlPagesSwitchPostErrors, SwitchPageApiV1RpaBrowserControlPagesSwitchPostResponses } from '../types.gen';

export class WebRtc视频流Service {
    /**
     * Get Pages List
     *
     * 获取浏览器所有页面列表
     *
     * 返回指定浏览器实例的所有页面信息，包括URL、标题等。
     *
     * Args:
     * browser_info: 浏览器认证信息
     *
     * Returns:
     * dict: 页面列表信息
     */
    public static getPagesListApiV1RpaBrowserControlPagesListPost<ThrowOnError extends boolean = false>(options: Options<GetPagesListApiV1RpaBrowserControlPagesListPostData, ThrowOnError>): RequestResult<GetPagesListApiV1RpaBrowserControlPagesListPostResponses, GetPagesListApiV1RpaBrowserControlPagesListPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<GetPagesListApiV1RpaBrowserControlPagesListPostResponses, GetPagesListApiV1RpaBrowserControlPagesListPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/pages/list',
            ...options
        });
    }
    
    /**
     * Switch Page
     *
     * 切换到指定页面
     *
     * 将浏览器的当前活动页面切换到指定索引的页面。
     *
     * Args:
     * request: 包含 page_index 的请求体
     * browser_info: 浏览器认证信息
     *
     * Returns:
     * dict: 切换结果
     */
    public static switchPageApiV1RpaBrowserControlPagesSwitchPost<ThrowOnError extends boolean = false>(options: Options<SwitchPageApiV1RpaBrowserControlPagesSwitchPostData, ThrowOnError>): RequestResult<SwitchPageApiV1RpaBrowserControlPagesSwitchPostResponses, SwitchPageApiV1RpaBrowserControlPagesSwitchPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<SwitchPageApiV1RpaBrowserControlPagesSwitchPostResponses, SwitchPageApiV1RpaBrowserControlPagesSwitchPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/pages/switch',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Close Page
     *
     * 关闭指定页面
     *
     * 关闭指定索引的页面。如果关闭后没有页面了，会创建一个新的空白页面。
     *
     * Args:
     * request: 包含 page_index 的请求体
     * browser_info: 浏览器认证信息
     *
     * Returns:
     * dict: 关闭结果
     */
    public static closePageApiV1RpaBrowserControlPagesClosePost<ThrowOnError extends boolean = false>(options: Options<ClosePageApiV1RpaBrowserControlPagesClosePostData, ThrowOnError>): RequestResult<ClosePageApiV1RpaBrowserControlPagesClosePostResponses, ClosePageApiV1RpaBrowserControlPagesClosePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ClosePageApiV1RpaBrowserControlPagesClosePostResponses, ClosePageApiV1RpaBrowserControlPagesClosePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/pages/close',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 创建 WebRTC Offer
     *
     * 创建 WebRTC Offer 以开始视频流传输。
     * 会话不存在时自动创建，WebRTC 管理器已内建无需手动启用。
     */
    public static createWebrtcOfferApiV1RpaBrowserControlWebrtcOfferPost<ThrowOnError extends boolean = false>(options: Options<CreateWebrtcOfferApiV1RpaBrowserControlWebrtcOfferPostData, ThrowOnError>): RequestResult<CreateWebrtcOfferApiV1RpaBrowserControlWebrtcOfferPostResponses, CreateWebrtcOfferApiV1RpaBrowserControlWebrtcOfferPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<CreateWebrtcOfferApiV1RpaBrowserControlWebrtcOfferPostResponses, CreateWebrtcOfferApiV1RpaBrowserControlWebrtcOfferPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/webrtc/offer',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 处理 WebRTC Answer
     *
     * 处理客户端返回的 SDP Answer（O(1) 流查找）
     */
    public static handleWebrtcAnswerApiV1RpaBrowserControlWebrtcAnswerPost<ThrowOnError extends boolean = false>(options: Options<HandleWebrtcAnswerApiV1RpaBrowserControlWebrtcAnswerPostData, ThrowOnError>): RequestResult<HandleWebrtcAnswerApiV1RpaBrowserControlWebrtcAnswerPostResponses, HandleWebrtcAnswerApiV1RpaBrowserControlWebrtcAnswerPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<HandleWebrtcAnswerApiV1RpaBrowserControlWebrtcAnswerPostResponses, HandleWebrtcAnswerApiV1RpaBrowserControlWebrtcAnswerPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/webrtc/answer',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 添加 ICE Candidate
     *
     * 添加 ICE Candidate（O(1) 流查找）
     */
    public static addIceCandidateApiV1RpaBrowserControlWebrtcIceCandidatePost<ThrowOnError extends boolean = false>(options: Options<AddIceCandidateApiV1RpaBrowserControlWebrtcIceCandidatePostData, ThrowOnError>): RequestResult<AddIceCandidateApiV1RpaBrowserControlWebrtcIceCandidatePostResponses, AddIceCandidateApiV1RpaBrowserControlWebrtcIceCandidatePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<AddIceCandidateApiV1RpaBrowserControlWebrtcIceCandidatePostResponses, AddIceCandidateApiV1RpaBrowserControlWebrtcIceCandidatePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/webrtc/ice-candidate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 关闭 WebRTC 流
     *
     * 关闭指定的 WebRTC 视频流（O(1) 查找 + 自动清理双索引）
     */
    public static closeWebrtcStreamApiV1RpaBrowserControlWebrtcClosePost<ThrowOnError extends boolean = false>(options: Options<CloseWebrtcStreamApiV1RpaBrowserControlWebrtcClosePostData, ThrowOnError>): RequestResult<CloseWebrtcStreamApiV1RpaBrowserControlWebrtcClosePostResponses, CloseWebrtcStreamApiV1RpaBrowserControlWebrtcClosePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<CloseWebrtcStreamApiV1RpaBrowserControlWebrtcClosePostResponses, CloseWebrtcStreamApiV1RpaBrowserControlWebrtcClosePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/webrtc/close',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 获取 WebRTC 流状态
     *
     * 获取当前浏览器会话的 WebRTC 流状态信息
     */
    public static getWebrtcStatusApiV1RpaBrowserControlWebrtcStatusPost<ThrowOnError extends boolean = false>(options: Options<GetWebrtcStatusApiV1RpaBrowserControlWebrtcStatusPostData, ThrowOnError>): RequestResult<GetWebrtcStatusApiV1RpaBrowserControlWebrtcStatusPostResponses, GetWebrtcStatusApiV1RpaBrowserControlWebrtcStatusPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<GetWebrtcStatusApiV1RpaBrowserControlWebrtcStatusPostResponses, GetWebrtcStatusApiV1RpaBrowserControlWebrtcStatusPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/webrtc/status',
            ...options
        });
    }
}
