// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { ExecuteActionApiV1RpaBrowserControlActionsExecutePostData, ExecuteActionApiV1RpaBrowserControlActionsExecutePostErrors, ExecuteActionApiV1RpaBrowserControlActionsExecutePostResponses, ExecuteActionStepApiV1RpaBrowserControlActionsExecuteStepPostData, ExecuteActionStepApiV1RpaBrowserControlActionsExecuteStepPostErrors, ExecuteActionStepApiV1RpaBrowserControlActionsExecuteStepPostResponses, ExecuteWorkflowApiV1RpaBrowserControlWorkflowsExecutePostData, ExecuteWorkflowApiV1RpaBrowserControlWorkflowsExecutePostErrors, ExecuteWorkflowApiV1RpaBrowserControlWorkflowsExecutePostResponses, ListSystemServicesApiV1RpaBrowserControlSystemServicesListGetData, ListSystemServicesApiV1RpaBrowserControlSystemServicesListGetResponses, PreviewActionParamsApiV1RpaBrowserControlActionsPreviewPostData, PreviewActionParamsApiV1RpaBrowserControlActionsPreviewPostErrors, PreviewActionParamsApiV1RpaBrowserControlActionsPreviewPostResponses, ValidateActionParamsApiV1RpaBrowserControlActionsValidatePostData, ValidateActionParamsApiV1RpaBrowserControlActionsValidatePostErrors, ValidateActionParamsApiV1RpaBrowserControlActionsValidatePostResponses } from '../types.gen';

export class 执行引擎Service {
    /**
     * 执行单个操作
     *
     * 执行单个操作
     */
    public static executeActionApiV1RpaBrowserControlActionsExecutePost<ThrowOnError extends boolean = false>(options: Options<ExecuteActionApiV1RpaBrowserControlActionsExecutePostData, ThrowOnError>): RequestResult<ExecuteActionApiV1RpaBrowserControlActionsExecutePostResponses, ExecuteActionApiV1RpaBrowserControlActionsExecutePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ExecuteActionApiV1RpaBrowserControlActionsExecutePostResponses, ExecuteActionApiV1RpaBrowserControlActionsExecutePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/actions/execute',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 执行工作流
     *
     * 执行工作流
     *
     * 支持两种模式：
     * - 提供 action_id：执行已保存的自定义操作
     * - 提供 steps：执行内联步骤（无需保存）
     */
    public static executeWorkflowApiV1RpaBrowserControlWorkflowsExecutePost<ThrowOnError extends boolean = false>(options: Options<ExecuteWorkflowApiV1RpaBrowserControlWorkflowsExecutePostData, ThrowOnError>): RequestResult<ExecuteWorkflowApiV1RpaBrowserControlWorkflowsExecutePostResponses, ExecuteWorkflowApiV1RpaBrowserControlWorkflowsExecutePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ExecuteWorkflowApiV1RpaBrowserControlWorkflowsExecutePostResponses, ExecuteWorkflowApiV1RpaBrowserControlWorkflowsExecutePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/workflows/execute',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 预览参数替换结果
     *
     * 预览参数替换结果
     */
    public static previewActionParamsApiV1RpaBrowserControlActionsPreviewPost<ThrowOnError extends boolean = false>(options: Options<PreviewActionParamsApiV1RpaBrowserControlActionsPreviewPostData, ThrowOnError>): RequestResult<PreviewActionParamsApiV1RpaBrowserControlActionsPreviewPostResponses, PreviewActionParamsApiV1RpaBrowserControlActionsPreviewPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<PreviewActionParamsApiV1RpaBrowserControlActionsPreviewPostResponses, PreviewActionParamsApiV1RpaBrowserControlActionsPreviewPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/actions/preview',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 验证操作参数
     *
     * 验证操作参数
     */
    public static validateActionParamsApiV1RpaBrowserControlActionsValidatePost<ThrowOnError extends boolean = false>(options: Options<ValidateActionParamsApiV1RpaBrowserControlActionsValidatePostData, ThrowOnError>): RequestResult<ValidateActionParamsApiV1RpaBrowserControlActionsValidatePostResponses, ValidateActionParamsApiV1RpaBrowserControlActionsValidatePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ValidateActionParamsApiV1RpaBrowserControlActionsValidatePostResponses, ValidateActionParamsApiV1RpaBrowserControlActionsValidatePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/actions/validate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 单步执行操作
     *
     * 单步执行操作
     *
     * 用于复合操作的逐步执行或调试。
     * - 如果 action_id 是复合操作，执行指定 step_index 的步骤
     * - 如果 action_id 是普通操作，执行该操作
     */
    public static executeActionStepApiV1RpaBrowserControlActionsExecuteStepPost<ThrowOnError extends boolean = false>(options: Options<ExecuteActionStepApiV1RpaBrowserControlActionsExecuteStepPostData, ThrowOnError>): RequestResult<ExecuteActionStepApiV1RpaBrowserControlActionsExecuteStepPostResponses, ExecuteActionStepApiV1RpaBrowserControlActionsExecuteStepPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ExecuteActionStepApiV1RpaBrowserControlActionsExecuteStepPostResponses, ExecuteActionStepApiV1RpaBrowserControlActionsExecuteStepPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/actions/execute-step',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 获取可用的系统 RPC 方法列表
     *
     * 获取获取外部数据 Action 可选的 RPC 业务方法列表
     *
     * 前端在配置获取外部数据 Action 时，应从该接口获取可选方法列表作为可选项展示，
     * 不允许用户随意输入外部方法名。每个方法对应一个独立的 RabbitMQ routing_key，
     * 由 FastapiApp 侧 RPC 服务端处理。
     */
    public static listSystemServicesApiV1RpaBrowserControlSystemServicesListGet<ThrowOnError extends boolean = false>(options?: Options<ListSystemServicesApiV1RpaBrowserControlSystemServicesListGetData, ThrowOnError>): RequestResult<ListSystemServicesApiV1RpaBrowserControlSystemServicesListGetResponses, unknown, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<ListSystemServicesApiV1RpaBrowserControlSystemServicesListGetResponses, unknown, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/system-services/list',
            ...options
        });
    }
}
