// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { ClearActionLogsApiV1RpaBrowserControlActionLogsClearPostData, ClearActionLogsApiV1RpaBrowserControlActionLogsClearPostErrors, ClearActionLogsApiV1RpaBrowserControlActionLogsClearPostResponses, DeleteActionLogsApiV1RpaBrowserControlActionLogsDeletePostData, DeleteActionLogsApiV1RpaBrowserControlActionLogsDeletePostErrors, DeleteActionLogsApiV1RpaBrowserControlActionLogsDeletePostResponses, GetActionLogApiV1RpaBrowserControlActionLogsGetPostData, GetActionLogApiV1RpaBrowserControlActionLogsGetPostErrors, GetActionLogApiV1RpaBrowserControlActionLogsGetPostResponses, ListActionLogsApiV1RpaBrowserControlActionLogsListPostData, ListActionLogsApiV1RpaBrowserControlActionLogsListPostErrors, ListActionLogsApiV1RpaBrowserControlActionLogsListPostResponses, ListActionLogsByExecutionApiV1RpaBrowserControlActionLogsByExecutionPostData, ListActionLogsByExecutionApiV1RpaBrowserControlActionLogsByExecutionPostErrors, ListActionLogsByExecutionApiV1RpaBrowserControlActionLogsByExecutionPostResponses, StatsActionLogsApiV1RpaBrowserControlActionLogsStatsPostData, StatsActionLogsApiV1RpaBrowserControlActionLogsStatsPostErrors, StatsActionLogsApiV1RpaBrowserControlActionLogsStatsPostResponses } from '../types.gen';

export class 操作日志管理Service {
    /**
     * 查询操作日志列表
     *
     * 按筛选条件查询操作日志（分页）
     *
     * 支持 action_id / execution_id / workflow_id / browser_id / source / status /
     * success / 关键字 / 时间范围筛选。
     */
    public static listActionLogsApiV1RpaBrowserControlActionLogsListPost<ThrowOnError extends boolean = false>(options: Options<ListActionLogsApiV1RpaBrowserControlActionLogsListPostData, ThrowOnError>): RequestResult<ListActionLogsApiV1RpaBrowserControlActionLogsListPostResponses, ListActionLogsApiV1RpaBrowserControlActionLogsListPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ListActionLogsApiV1RpaBrowserControlActionLogsListPostResponses, ListActionLogsApiV1RpaBrowserControlActionLogsListPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/action-logs/list',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 获取单条日志详情
     *
     * 按 log_id 获取单条日志详情
     */
    public static getActionLogApiV1RpaBrowserControlActionLogsGetPost<ThrowOnError extends boolean = false>(options: Options<GetActionLogApiV1RpaBrowserControlActionLogsGetPostData, ThrowOnError>): RequestResult<GetActionLogApiV1RpaBrowserControlActionLogsGetPostResponses, GetActionLogApiV1RpaBrowserControlActionLogsGetPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<GetActionLogApiV1RpaBrowserControlActionLogsGetPostResponses, GetActionLogApiV1RpaBrowserControlActionLogsGetPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/action-logs/get',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 按执行批次查询完整链路
     *
     * 按 execution_id 拉取一次执行的完整链路（按写入顺序，便于还原调用树）
     */
    public static listActionLogsByExecutionApiV1RpaBrowserControlActionLogsByExecutionPost<ThrowOnError extends boolean = false>(options: Options<ListActionLogsByExecutionApiV1RpaBrowserControlActionLogsByExecutionPostData, ThrowOnError>): RequestResult<ListActionLogsByExecutionApiV1RpaBrowserControlActionLogsByExecutionPostResponses, ListActionLogsByExecutionApiV1RpaBrowserControlActionLogsByExecutionPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ListActionLogsByExecutionApiV1RpaBrowserControlActionLogsByExecutionPostResponses, ListActionLogsByExecutionApiV1RpaBrowserControlActionLogsByExecutionPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/action-logs/by-execution',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 批量删除日志
     *
     * 按 log_id 列表批量删除日志
     */
    public static deleteActionLogsApiV1RpaBrowserControlActionLogsDeletePost<ThrowOnError extends boolean = false>(options: Options<DeleteActionLogsApiV1RpaBrowserControlActionLogsDeletePostData, ThrowOnError>): RequestResult<DeleteActionLogsApiV1RpaBrowserControlActionLogsDeletePostResponses, DeleteActionLogsApiV1RpaBrowserControlActionLogsDeletePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<DeleteActionLogsApiV1RpaBrowserControlActionLogsDeletePostResponses, DeleteActionLogsApiV1RpaBrowserControlActionLogsDeletePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/action-logs/delete',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 按条件清空日志
     *
     * 按筛选条件批量清空日志
     */
    public static clearActionLogsApiV1RpaBrowserControlActionLogsClearPost<ThrowOnError extends boolean = false>(options: Options<ClearActionLogsApiV1RpaBrowserControlActionLogsClearPostData, ThrowOnError>): RequestResult<ClearActionLogsApiV1RpaBrowserControlActionLogsClearPostResponses, ClearActionLogsApiV1RpaBrowserControlActionLogsClearPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ClearActionLogsApiV1RpaBrowserControlActionLogsClearPostResponses, ClearActionLogsApiV1RpaBrowserControlActionLogsClearPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/action-logs/clear',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 操作日志统计
     *
     * 按 action 聚合统计最近 N 天的执行情况（默认 7 天）
     */
    public static statsActionLogsApiV1RpaBrowserControlActionLogsStatsPost<ThrowOnError extends boolean = false>(options?: Options<StatsActionLogsApiV1RpaBrowserControlActionLogsStatsPostData, ThrowOnError>): RequestResult<StatsActionLogsApiV1RpaBrowserControlActionLogsStatsPostResponses, StatsActionLogsApiV1RpaBrowserControlActionLogsStatsPostErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).post<StatsActionLogsApiV1RpaBrowserControlActionLogsStatsPostResponses, StatsActionLogsApiV1RpaBrowserControlActionLogsStatsPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/action-logs/stats',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}
