// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { CountFingerprintRouterApiV1RpaBrowserCountFingerprintPostData, CountFingerprintRouterApiV1RpaBrowserCountFingerprintPostErrors, CountFingerprintRouterApiV1RpaBrowserCountFingerprintPostResponses, DeleteFingerprintRouterApiV1RpaBrowserDeleteFingerprintPostData, DeleteFingerprintRouterApiV1RpaBrowserDeleteFingerprintPostErrors, DeleteFingerprintRouterApiV1RpaBrowserDeleteFingerprintPostResponses, GenRandFingerprintRouterApiV1RpaBrowserGenRandFingerprintPostData, GenRandFingerprintRouterApiV1RpaBrowserGenRandFingerprintPostErrors, GenRandFingerprintRouterApiV1RpaBrowserGenRandFingerprintPostResponses, ListFingerprintRouterApiV1RpaBrowserListFingerprintPostData, ListFingerprintRouterApiV1RpaBrowserListFingerprintPostErrors, ListFingerprintRouterApiV1RpaBrowserListFingerprintPostResponses, ReadFingerprintRouterApiV1RpaBrowserReadFingerprintPostData, ReadFingerprintRouterApiV1RpaBrowserReadFingerprintPostErrors, ReadFingerprintRouterApiV1RpaBrowserReadFingerprintPostResponses, RenameFingerprintRouterApiV1RpaBrowserRenameFingerprintPostData, RenameFingerprintRouterApiV1RpaBrowserRenameFingerprintPostErrors, RenameFingerprintRouterApiV1RpaBrowserRenameFingerprintPostResponses, UpsertFingerprintRouterApiV1RpaBrowserUpsertFingerprintPostData, UpsertFingerprintRouterApiV1RpaBrowserUpsertFingerprintPostErrors, UpsertFingerprintRouterApiV1RpaBrowserUpsertFingerprintPostResponses } from '../types.gen';

export class 浏览器指纹管理Service {
    /**
     * Gen Rand Fingerprint Router
     *
     * 生成随机浏览器指纹信息（不保存到数据库）
     *
     * 生成一个随机的浏览器指纹配置，用于临时使用或测试。此接口不会将指纹信息保存到数据库中。
     * 支持自定义浏览器类型、操作系统、设备类型等参数，如果不指定则随机生成。
     *
     * Args:
     * params: 浏览器指纹创建参数，包括浏览器类型、操作系统、设备类型等配置
     *
     * Returns:
     * dict: 包含随机生成的浏览器指纹信息的字典，包括用户代理、屏幕分辨率、时区、语言等信息
     *
     * Note:
     * 此接口仅生成临时指纹，不会持久化存储。如需保存指纹，请使用 upsert_fingerprint 接口
     */
    public static genRandFingerprintRouterApiV1RpaBrowserGenRandFingerprintPost<ThrowOnError extends boolean = false>(options?: Options<GenRandFingerprintRouterApiV1RpaBrowserGenRandFingerprintPostData, ThrowOnError>): RequestResult<GenRandFingerprintRouterApiV1RpaBrowserGenRandFingerprintPostResponses, GenRandFingerprintRouterApiV1RpaBrowserGenRandFingerprintPostErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).post<GenRandFingerprintRouterApiV1RpaBrowserGenRandFingerprintPostResponses, GenRandFingerprintRouterApiV1RpaBrowserGenRandFingerprintPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/gen_rand_fingerprint',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Upsert Fingerprint Router
     *
     * 创建或更新浏览器指纹信息 (upsert)
     *
     * 如果提供了 id 则更新现有记录，否则创建新记录。
     * 创建时会生成一个随机的浏览器指纹配置并保存到数据库中，创建的指纹信息可以用于后续的浏览器实例启动。
     * 更新时会根据提供的 id 和需要更新的字段进行更新。
     * 支持自定义浏览器类型、操作系统、设备类型等参数，如果不指定则随机生成。
     *
     * Args:
     * params: 浏览器指纹创建或更新参数，包括 id（可选）和各种浏览器配置
     * auth_info: 认证信息，从请求头中自动获取
     * session: 数据库会话
     *
     * Returns:
     * BrowserFingerprintCreateResp: 创建或更新成功的浏览器指纹信息，包含数据库ID等
     *
     * Note:
     * 创建或更新的指纹信息会持久化保存，可用于浏览器实例的指纹配置
     * 更新操作时只能更新属于当前用户的浏览器指纹信息
     * 创建新指纹时会检查当前等级的指纹数量限制
     */
    public static upsertFingerprintRouterApiV1RpaBrowserUpsertFingerprintPost<ThrowOnError extends boolean = false>(options: Options<UpsertFingerprintRouterApiV1RpaBrowserUpsertFingerprintPostData, ThrowOnError>): RequestResult<UpsertFingerprintRouterApiV1RpaBrowserUpsertFingerprintPostResponses, UpsertFingerprintRouterApiV1RpaBrowserUpsertFingerprintPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<UpsertFingerprintRouterApiV1RpaBrowserUpsertFingerprintPostResponses, UpsertFingerprintRouterApiV1RpaBrowserUpsertFingerprintPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/upsert_fingerprint',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Read Fingerprint Router
     *
     * 读取指定条件的浏览器指纹信息
     *
     * 根据提供的查询条件从数据库中读取浏览器指纹信息。支持按指纹ID、用户ID等多种条件查询。
     * 如果找到匹配的指纹信息则返回，否则返回None。
     *
     * Args:
     * params: 浏览器指纹查询参数，包括指纹ID等查询条件
     * auth_info: 认证信息，从请求头中自动获取
     * session: 数据库会话
     *
     * Returns:
     * Union[BrowserFingerprintQueryResp, None]: 找到的浏览器指纹信息，如果未找到则返回None
     *
     * Note:
     * 只能查询属于当前用户的浏览器指纹信息
     */
    public static readFingerprintRouterApiV1RpaBrowserReadFingerprintPost<ThrowOnError extends boolean = false>(options: Options<ReadFingerprintRouterApiV1RpaBrowserReadFingerprintPostData, ThrowOnError>): RequestResult<ReadFingerprintRouterApiV1RpaBrowserReadFingerprintPostResponses, ReadFingerprintRouterApiV1RpaBrowserReadFingerprintPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ReadFingerprintRouterApiV1RpaBrowserReadFingerprintPostResponses, ReadFingerprintRouterApiV1RpaBrowserReadFingerprintPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/read_fingerprint',
            ...options
        });
    }
    
    /**
     * Delete Fingerprint Router
     *
     * 删除指定的浏览器指纹信息
     *
     * 根据提供的指纹ID从数据库中永久删除浏览器指纹配置。删除操作不可恢复，请谨慎操作。
     * 只能删除属于当前用户的浏览器指纹信息。
     *
     * Args:
     * browser_info: 已验证的浏览器请求信息（通过依赖注入自动获取）
     * session: 数据库会话
     *
     * Returns:
     * BrowserFingerprintDeleteResp: 删除操作的结果，包含操作状态信息
     *
     * Note:
     * 删除操作不可恢复，请确保不再需要该指纹信息后再执行删除操作
     */
    public static deleteFingerprintRouterApiV1RpaBrowserDeleteFingerprintPost<ThrowOnError extends boolean = false>(options: Options<DeleteFingerprintRouterApiV1RpaBrowserDeleteFingerprintPostData, ThrowOnError>): RequestResult<DeleteFingerprintRouterApiV1RpaBrowserDeleteFingerprintPostResponses, DeleteFingerprintRouterApiV1RpaBrowserDeleteFingerprintPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<DeleteFingerprintRouterApiV1RpaBrowserDeleteFingerprintPostResponses, DeleteFingerprintRouterApiV1RpaBrowserDeleteFingerprintPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/delete_fingerprint',
            ...options
        });
    }
    
    /**
     * Count Fingerprint Router
     *
     * 统计当前用户的浏览器指纹数量
     *
     * 获取当前用户在数据库中保存的浏览器指纹信息的总数量。用于显示指纹管理页面的统计信息。
     *
     * Args:
     * auth_info: 认证信息，从请求头中自动获取
     * session: 数据库会话
     *
     * Returns:
     * int: 当前用户的浏览器指纹总数量
     *
     * Note:
     * 只统计属于当前用户的浏览器指纹信息
     */
    public static countFingerprintRouterApiV1RpaBrowserCountFingerprintPost<ThrowOnError extends boolean = false>(options?: Options<CountFingerprintRouterApiV1RpaBrowserCountFingerprintPostData, ThrowOnError>): RequestResult<CountFingerprintRouterApiV1RpaBrowserCountFingerprintPostResponses, CountFingerprintRouterApiV1RpaBrowserCountFingerprintPostErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).post<CountFingerprintRouterApiV1RpaBrowserCountFingerprintPostResponses, CountFingerprintRouterApiV1RpaBrowserCountFingerprintPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/count_fingerprint',
            ...options
        });
    }
    
    /**
     * List Fingerprint Router
     *
     * 分页列表显示当前用户的浏览器指纹信息
     *
     * 以分页形式获取当前用户的浏览器指纹信息列表。支持分页参数配置，包括页码、每页数量等。
     * 返回的信息包括指纹ID、创建时间、浏览器类型、操作系统等基本信息。
     *
     * Args:
     * params: 分页查询参数，包括页码、每页数量等
     * auth_info: 认证信息，从请求头中自动获取
     * session: 数据库会话
     *
     * Returns:
     * BasePaginationResp[UserBrowserInfo]: 分页的浏览器指纹列表，包含总数、页码等信息
     *
     * Note:
     * 只返回属于当前用户的浏览器指纹信息，按创建时间倒序排列
     */
    public static listFingerprintRouterApiV1RpaBrowserListFingerprintPost<ThrowOnError extends boolean = false>(options: Options<ListFingerprintRouterApiV1RpaBrowserListFingerprintPostData, ThrowOnError>): RequestResult<ListFingerprintRouterApiV1RpaBrowserListFingerprintPostResponses, ListFingerprintRouterApiV1RpaBrowserListFingerprintPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ListFingerprintRouterApiV1RpaBrowserListFingerprintPostResponses, ListFingerprintRouterApiV1RpaBrowserListFingerprintPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/list_fingerprint',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Rename Fingerprint Router
     *
     * 重命名浏览器指纹
     *
     * 更新指定浏览器指纹的自定义名称。支持设置新名称或清除名称（传入 null）。
     * 只能修改属于当前用户的浏览器指纹信息。
     *
     * Args:
     * params: 重命名参数，包含指纹ID和新名称
     * browser_info: 已验证的浏览器请求信息（通过依赖注入自动获取）
     * session: 数据库会话
     *
     * Returns:
     * BrowserFingerprintRenameResp: 更新结果，包含指纹ID和新名称
     *
     * Note:
     * 只能修改属于当前用户的浏览器指纹信息
     * 设置 custom_name 为 null 可清除名称
     */
    public static renameFingerprintRouterApiV1RpaBrowserRenameFingerprintPost<ThrowOnError extends boolean = false>(options: Options<RenameFingerprintRouterApiV1RpaBrowserRenameFingerprintPostData, ThrowOnError>): RequestResult<RenameFingerprintRouterApiV1RpaBrowserRenameFingerprintPostResponses, RenameFingerprintRouterApiV1RpaBrowserRenameFingerprintPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<RenameFingerprintRouterApiV1RpaBrowserRenameFingerprintPostResponses, RenameFingerprintRouterApiV1RpaBrowserRenameFingerprintPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/rename_fingerprint',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
