// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { ApplyDefaultSettingsToBrowserApiV1RpaBrowserDefaultSettingsApplyPostData, ApplyDefaultSettingsToBrowserApiV1RpaBrowserDefaultSettingsApplyPostErrors, ApplyDefaultSettingsToBrowserApiV1RpaBrowserDefaultSettingsApplyPostResponses, CreateOrUpdateUserDefaultSettingsApiV1RpaBrowserDefaultSettingsCreateOrUpdatePostData, CreateOrUpdateUserDefaultSettingsApiV1RpaBrowserDefaultSettingsCreateOrUpdatePostErrors, CreateOrUpdateUserDefaultSettingsApiV1RpaBrowserDefaultSettingsCreateOrUpdatePostResponses, DeleteUserDefaultSettingsApiV1RpaBrowserDefaultSettingsDeletePostData, DeleteUserDefaultSettingsApiV1RpaBrowserDefaultSettingsDeletePostErrors, DeleteUserDefaultSettingsApiV1RpaBrowserDefaultSettingsDeletePostResponses, GetServerDefaultSettingsApiV1RpaBrowserDefaultSettingsServerDefaultsGetPostData, GetServerDefaultSettingsApiV1RpaBrowserDefaultSettingsServerDefaultsGetPostResponses, GetUserDefaultSettingsApiV1RpaBrowserDefaultSettingsGetPostData, GetUserDefaultSettingsApiV1RpaBrowserDefaultSettingsGetPostErrors, GetUserDefaultSettingsApiV1RpaBrowserDefaultSettingsGetPostResponses } from '../types.gen';

export class 浏览器默认设置管理Service {
    /**
     * Get User Default Settings
     *
     * 获取用户的默认设置
     *
     * 如果用户没有设置过默认设置，返回 null
     */
    public static getUserDefaultSettingsApiV1RpaBrowserDefaultSettingsGetPost<ThrowOnError extends boolean = false>(options: Options<GetUserDefaultSettingsApiV1RpaBrowserDefaultSettingsGetPostData, ThrowOnError>): RequestResult<GetUserDefaultSettingsApiV1RpaBrowserDefaultSettingsGetPostResponses, GetUserDefaultSettingsApiV1RpaBrowserDefaultSettingsGetPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<GetUserDefaultSettingsApiV1RpaBrowserDefaultSettingsGetPostResponses, GetUserDefaultSettingsApiV1RpaBrowserDefaultSettingsGetPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/default-settings/get',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Create Or Update User Default Settings
     *
     * 创建或更新用户的默认设置
     *
     * 如果用户已有默认设置，则更新；否则创建新的默认设置
     */
    public static createOrUpdateUserDefaultSettingsApiV1RpaBrowserDefaultSettingsCreateOrUpdatePost<ThrowOnError extends boolean = false>(options: Options<CreateOrUpdateUserDefaultSettingsApiV1RpaBrowserDefaultSettingsCreateOrUpdatePostData, ThrowOnError>): RequestResult<CreateOrUpdateUserDefaultSettingsApiV1RpaBrowserDefaultSettingsCreateOrUpdatePostResponses, CreateOrUpdateUserDefaultSettingsApiV1RpaBrowserDefaultSettingsCreateOrUpdatePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<CreateOrUpdateUserDefaultSettingsApiV1RpaBrowserDefaultSettingsCreateOrUpdatePostResponses, CreateOrUpdateUserDefaultSettingsApiV1RpaBrowserDefaultSettingsCreateOrUpdatePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/default-settings/create-or-update',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete User Default Settings
     *
     * 删除用户的默认设置
     *
     * 成功删除返回 true，如果设置不存在返回 false
     */
    public static deleteUserDefaultSettingsApiV1RpaBrowserDefaultSettingsDeletePost<ThrowOnError extends boolean = false>(options: Options<DeleteUserDefaultSettingsApiV1RpaBrowserDefaultSettingsDeletePostData, ThrowOnError>): RequestResult<DeleteUserDefaultSettingsApiV1RpaBrowserDefaultSettingsDeletePostResponses, DeleteUserDefaultSettingsApiV1RpaBrowserDefaultSettingsDeletePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<DeleteUserDefaultSettingsApiV1RpaBrowserDefaultSettingsDeletePostResponses, DeleteUserDefaultSettingsApiV1RpaBrowserDefaultSettingsDeletePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/default-settings/delete',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Apply Default Settings To Browser
     *
     * 将用户的默认设置应用到指定的浏览器实例
     *
     * 将用户的默认设置（如代理、视口等）应用到指定的浏览器实例
     */
    public static applyDefaultSettingsToBrowserApiV1RpaBrowserDefaultSettingsApplyPost<ThrowOnError extends boolean = false>(options: Options<ApplyDefaultSettingsToBrowserApiV1RpaBrowserDefaultSettingsApplyPostData, ThrowOnError>): RequestResult<ApplyDefaultSettingsToBrowserApiV1RpaBrowserDefaultSettingsApplyPostResponses, ApplyDefaultSettingsToBrowserApiV1RpaBrowserDefaultSettingsApplyPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ApplyDefaultSettingsToBrowserApiV1RpaBrowserDefaultSettingsApplyPostResponses, ApplyDefaultSettingsToBrowserApiV1RpaBrowserDefaultSettingsApplyPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/default-settings/apply',
            ...options
        });
    }
    
    /**
     * Get Server Default Settings
     *
     * 获取服务端预定义的默认设置
     *
     * 返回服务器端的默认配置值，这些值用于在用户未设置时作为默认值
     */
    public static getServerDefaultSettingsApiV1RpaBrowserDefaultSettingsServerDefaultsGetPost<ThrowOnError extends boolean = false>(options?: Options<GetServerDefaultSettingsApiV1RpaBrowserDefaultSettingsServerDefaultsGetPostData, ThrowOnError>): RequestResult<GetServerDefaultSettingsApiV1RpaBrowserDefaultSettingsServerDefaultsGetPostResponses, unknown, ThrowOnError, 'data'> {
        return (options?.client ?? client).post<GetServerDefaultSettingsApiV1RpaBrowserDefaultSettingsServerDefaultsGetPostResponses, unknown, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/default-settings/server-defaults/get',
            ...options
        });
    }
}
