// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { BrowserSessionStatusApiV1RpaBrowserControlStatusPostData, BrowserSessionStatusApiV1RpaBrowserControlStatusPostErrors, BrowserSessionStatusApiV1RpaBrowserControlStatusPostResponses, CloseBrowserSessionApiV1RpaBrowserControlClosePostData, CloseBrowserSessionApiV1RpaBrowserControlClosePostErrors, CloseBrowserSessionApiV1RpaBrowserControlClosePostResponses, CreateBrowserSessionApiV1RpaBrowserControlCreatePostData, CreateBrowserSessionApiV1RpaBrowserControlCreatePostErrors, CreateBrowserSessionApiV1RpaBrowserControlCreatePostResponses } from '../types.gen';

export class 浏览器会话控制Service {
    /**
     * Create Browser Session
     *
     * 创建浏览器会话
     *
     * 独立的会话创建接口，与心跳机制完全解耦。
     * 如果浏览器未运行，将创建任务添加到后台任务中异步执行，立即返回响应。
     *
     * Args:
     * request: 会话创建参数请求
     * background_tasks: FastAPI 后台任务
     *
     * Returns:
     * CreateSessionResponse: 会话创建结果
     */
    public static createBrowserSessionApiV1RpaBrowserControlCreatePost<ThrowOnError extends boolean = false>(options: Options<CreateBrowserSessionApiV1RpaBrowserControlCreatePostData, ThrowOnError>): RequestResult<CreateBrowserSessionApiV1RpaBrowserControlCreatePostResponses, CreateBrowserSessionApiV1RpaBrowserControlCreatePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<CreateBrowserSessionApiV1RpaBrowserControlCreatePostResponses, CreateBrowserSessionApiV1RpaBrowserControlCreatePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/create',
            ...options
        });
    }
    
    /**
     * Browser Session Status
     *
     * 获取浏览器会话状态
     *
     * 提供统一的会话状态查询，包含所有相关的状态信息。
     * 可以用来检查会话是否存在、浏览器是否运行、生命周期状态等。
     *
     * Returns:
     * BrowserSessionStatus: 会话状态信息
     */
    public static browserSessionStatusApiV1RpaBrowserControlStatusPost<ThrowOnError extends boolean = false>(options: Options<BrowserSessionStatusApiV1RpaBrowserControlStatusPostData, ThrowOnError>): RequestResult<BrowserSessionStatusApiV1RpaBrowserControlStatusPostResponses, BrowserSessionStatusApiV1RpaBrowserControlStatusPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<BrowserSessionStatusApiV1RpaBrowserControlStatusPostResponses, BrowserSessionStatusApiV1RpaBrowserControlStatusPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/status',
            ...options
        });
    }
    
    /**
     * Close Browser Session
     *
     * 手动关闭浏览器会话
     *
     * 主动关闭指定的浏览器会话，释放相关资源。
     * 如果会话不存在，将返回错误响应。
     *
     * Returns:
     * CloseSessionResponse: 会话关闭结果
     */
    public static closeBrowserSessionApiV1RpaBrowserControlClosePost<ThrowOnError extends boolean = false>(options: Options<CloseBrowserSessionApiV1RpaBrowserControlClosePostData, ThrowOnError>): RequestResult<CloseBrowserSessionApiV1RpaBrowserControlClosePostResponses, CloseBrowserSessionApiV1RpaBrowserControlClosePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<CloseBrowserSessionApiV1RpaBrowserControlClosePostResponses, CloseBrowserSessionApiV1RpaBrowserControlClosePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/close',
            ...options
        });
    }
}
