// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { ClosePageApiV1RpaBrowserControlOperationClosePagePostData, ClosePageApiV1RpaBrowserControlOperationClosePagePostErrors, ClosePageApiV1RpaBrowserControlOperationClosePagePostResponses, GetBrowserInfoApiV1RpaBrowserControlBrowserInfoPostData, GetBrowserInfoApiV1RpaBrowserControlBrowserInfoPostErrors, GetBrowserInfoApiV1RpaBrowserControlBrowserInfoPostResponses, GetPageInfoApiV1RpaBrowserControlOperationGetPageInfoPostData, GetPageInfoApiV1RpaBrowserControlOperationGetPageInfoPostErrors, GetPageInfoApiV1RpaBrowserControlOperationGetPageInfoPostResponses, OpenPageApiV1RpaBrowserControlOperationOpenPagePostData, OpenPageApiV1RpaBrowserControlOperationOpenPagePostErrors, OpenPageApiV1RpaBrowserControlOperationOpenPagePostResponses, SwitchPageApiV1RpaBrowserControlOperationSwitchPagePostData, SwitchPageApiV1RpaBrowserControlOperationSwitchPagePostErrors, SwitchPageApiV1RpaBrowserControlOperationSwitchPagePostResponses } from '../types.gen';

export class 自动化控制Service {
    /**
     * 打开页面
     *
     * 在浏览器中打开指定URL
     */
    public static openPageApiV1RpaBrowserControlOperationOpenPagePost<ThrowOnError extends boolean = false>(options: Options<OpenPageApiV1RpaBrowserControlOperationOpenPagePostData, ThrowOnError>): RequestResult<OpenPageApiV1RpaBrowserControlOperationOpenPagePostResponses, OpenPageApiV1RpaBrowserControlOperationOpenPagePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<OpenPageApiV1RpaBrowserControlOperationOpenPagePostResponses, OpenPageApiV1RpaBrowserControlOperationOpenPagePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/operation/open_page',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 关闭页面
     *
     * 关闭指定页面
     */
    public static closePageApiV1RpaBrowserControlOperationClosePagePost<ThrowOnError extends boolean = false>(options: Options<ClosePageApiV1RpaBrowserControlOperationClosePagePostData, ThrowOnError>): RequestResult<ClosePageApiV1RpaBrowserControlOperationClosePagePostResponses, ClosePageApiV1RpaBrowserControlOperationClosePagePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ClosePageApiV1RpaBrowserControlOperationClosePagePostResponses, ClosePageApiV1RpaBrowserControlOperationClosePagePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/operation/close_page',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 切换页面
     *
     * 切换到指定页面
     */
    public static switchPageApiV1RpaBrowserControlOperationSwitchPagePost<ThrowOnError extends boolean = false>(options: Options<SwitchPageApiV1RpaBrowserControlOperationSwitchPagePostData, ThrowOnError>): RequestResult<SwitchPageApiV1RpaBrowserControlOperationSwitchPagePostResponses, SwitchPageApiV1RpaBrowserControlOperationSwitchPagePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<SwitchPageApiV1RpaBrowserControlOperationSwitchPagePostResponses, SwitchPageApiV1RpaBrowserControlOperationSwitchPagePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/operation/switch_page',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 获取页面信息
     *
     * 获取指定页面的信息
     */
    public static getPageInfoApiV1RpaBrowserControlOperationGetPageInfoPost<ThrowOnError extends boolean = false>(options: Options<GetPageInfoApiV1RpaBrowserControlOperationGetPageInfoPostData, ThrowOnError>): RequestResult<GetPageInfoApiV1RpaBrowserControlOperationGetPageInfoPostResponses, GetPageInfoApiV1RpaBrowserControlOperationGetPageInfoPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<GetPageInfoApiV1RpaBrowserControlOperationGetPageInfoPostResponses, GetPageInfoApiV1RpaBrowserControlOperationGetPageInfoPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/operation/get_page_info',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 获取浏览器信息
     *
     * 获取当前浏览器实例的详细信息
     */
    public static getBrowserInfoApiV1RpaBrowserControlBrowserInfoPost<ThrowOnError extends boolean = false>(options: Options<GetBrowserInfoApiV1RpaBrowserControlBrowserInfoPostData, ThrowOnError>): RequestResult<GetBrowserInfoApiV1RpaBrowserControlBrowserInfoPostResponses, GetBrowserInfoApiV1RpaBrowserControlBrowserInfoPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<GetBrowserInfoApiV1RpaBrowserControlBrowserInfoPostResponses, GetBrowserInfoApiV1RpaBrowserControlBrowserInfoPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa/browser/control/browser/info',
            ...options
        });
    }
}
