// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { TestMsgPubRabbitmqTestPublishPostData, TestMsgPubRabbitmqTestPublishPostErrors, TestMsgPubRabbitmqTestPublishPostResponses } from '../types.gen';

export class Mq测试Service {
    /**
     *  Test Msg Pub
     */
    public static testMsgPubRabbitmqTestPublishPost<ThrowOnError extends boolean = false>(options?: Options<TestMsgPubRabbitmqTestPublishPostData, ThrowOnError>): RequestResult<TestMsgPubRabbitmqTestPublishPostResponses, TestMsgPubRabbitmqTestPublishPostErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).post<TestMsgPubRabbitmqTestPublishPostResponses, TestMsgPubRabbitmqTestPublishPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/rabbitmq_test_publish',
            ...options
        });
    }
}
