// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { HandleHttpGetApiV1SamsClubGraphqlGetData, HandleHttpGetApiV1SamsClubGraphqlGetErrors, HandleHttpGetApiV1SamsClubGraphqlGetResponses, HandleHttpPostApiV1SamsClubGraphqlPostData, HandleHttpPostApiV1SamsClubGraphqlPostResponses, SamsclubApiStatusApiV1SamsClubSamsclubApiStatusGetData, SamsclubApiStatusApiV1SamsClubSamsclubApiStatusGetResponses, SetNewAuthTokenApiV1SamsClubSetNewAuthTokenPostData, SetNewAuthTokenApiV1SamsClubSetNewAuthTokenPostErrors, SetNewAuthTokenApiV1SamsClubSetNewAuthTokenPostResponses } from '../types.gen';

export class SamsClubService {
    /**
     * Set New Auth Token
     *
     * 更新samsclub爬虫的auth_token
     */
    public static setNewAuthTokenApiV1SamsClubSetNewAuthTokenPost<ThrowOnError extends boolean = false>(options: Options<SetNewAuthTokenApiV1SamsClubSetNewAuthTokenPostData, ThrowOnError>): RequestResult<SetNewAuthTokenApiV1SamsClubSetNewAuthTokenPostResponses, SetNewAuthTokenApiV1SamsClubSetNewAuthTokenPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<SetNewAuthTokenApiV1SamsClubSetNewAuthTokenPostResponses, SetNewAuthTokenApiV1SamsClubSetNewAuthTokenPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/samsClub/set_new_auth_token',
            ...options
        });
    }
    
    /**
     * Handle Http Get
     */
    public static handleHttpGetApiV1SamsClubGraphqlGet<ThrowOnError extends boolean = false>(options?: Options<HandleHttpGetApiV1SamsClubGraphqlGetData, ThrowOnError>): RequestResult<HandleHttpGetApiV1SamsClubGraphqlGetResponses, HandleHttpGetApiV1SamsClubGraphqlGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<HandleHttpGetApiV1SamsClubGraphqlGetResponses, HandleHttpGetApiV1SamsClubGraphqlGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/samsClub/graphql',
            ...options
        });
    }
    
    /**
     * Handle Http Post
     */
    public static handleHttpPostApiV1SamsClubGraphqlPost<ThrowOnError extends boolean = false>(options?: Options<HandleHttpPostApiV1SamsClubGraphqlPostData, ThrowOnError>): RequestResult<HandleHttpPostApiV1SamsClubGraphqlPostResponses, unknown, ThrowOnError, 'data'> {
        return (options?.client ?? client).post<HandleHttpPostApiV1SamsClubGraphqlPostResponses, unknown, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/samsClub/graphql',
            ...options
        });
    }
    
    /**
     * Samsclub Api Status
     */
    public static samsclubApiStatusApiV1SamsClubSamsclubApiStatusGet<ThrowOnError extends boolean = false>(options?: Options<SamsclubApiStatusApiV1SamsClubSamsclubApiStatusGetData, ThrowOnError>): RequestResult<SamsclubApiStatusApiV1SamsClubSamsclubApiStatusGetResponses, unknown, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<SamsclubApiStatusApiV1SamsClubSamsclubApiStatusGetResponses, unknown, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/samsClub/samsclub_api_status',
            ...options
        });
    }
}
