// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { TestPushErrorTestPushErrorGetData, TestPushErrorTestPushErrorGetResponses } from '../types.gen';

export class 消息推送微服务Service {
    /**
     * Test Push Error
     *
     * 测试接口：故意抛错，并向消息推送微服务(message-service)发送一条测试告警，用于验证「异常 -> RabbitMQ(message 队列) -> message-service -> PushMe/PushPlus」推送链路是否正常
     */
    public static testPushErrorTestPushErrorGet<ThrowOnError extends boolean = false>(options?: Options<TestPushErrorTestPushErrorGetData, ThrowOnError>): RequestResult<TestPushErrorTestPushErrorGetResponses, unknown, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<TestPushErrorTestPushErrorGetResponses, unknown, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/test_push_error',
            ...options
        });
    }
}
