// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { DownloadAppJsonSchemaAsyncapiJsonGetData, DownloadAppJsonSchemaAsyncapiJsonGetResponses, DownloadAppYamlSchemaAsyncapiYamlGetData, DownloadAppYamlSchemaAsyncapiYamlGetResponses, ServeAsyncapiSchemaAsyncapiGetData, ServeAsyncapiSchemaAsyncapiGetErrors, ServeAsyncapiSchemaAsyncapiGetResponses } from '../types.gen';

export class AsyncapiService {
    /**
     * Serve Asyncapi Schema
     *
     * Serve the AsyncAPI schema as an HTML response.
     */
    public static serveAsyncapiSchemaAsyncapiGet<ThrowOnError extends boolean = false>(options?: Options<ServeAsyncapiSchemaAsyncapiGetData, ThrowOnError>): RequestResult<ServeAsyncapiSchemaAsyncapiGetResponses, ServeAsyncapiSchemaAsyncapiGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<ServeAsyncapiSchemaAsyncapiGetResponses, ServeAsyncapiSchemaAsyncapiGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/asyncapi',
            ...options
        });
    }
    
    /**
     * Download App Json Schema
     */
    public static downloadAppJsonSchemaAsyncapiJsonGet<ThrowOnError extends boolean = false>(options?: Options<DownloadAppJsonSchemaAsyncapiJsonGetData, ThrowOnError>): RequestResult<DownloadAppJsonSchemaAsyncapiJsonGetResponses, unknown, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<DownloadAppJsonSchemaAsyncapiJsonGetResponses, unknown, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/asyncapi.json',
            ...options
        });
    }
    
    /**
     * Download App Yaml Schema
     */
    public static downloadAppYamlSchemaAsyncapiYamlGet<ThrowOnError extends boolean = false>(options?: Options<DownloadAppYamlSchemaAsyncapiYamlGetData, ThrowOnError>): RequestResult<DownloadAppYamlSchemaAsyncapiYamlGetResponses, unknown, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<DownloadAppYamlSchemaAsyncapiYamlGetResponses, unknown, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/asyncapi.yaml',
            ...options
        });
    }
}
