// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AdminIpApiV1CommentAdminIpRpidGetData, AdminIpApiV1CommentAdminIpRpidGetErrors, AdminIpApiV1CommentAdminIpRpidGetResponses, AdminStatsApiV1CommentAdminStatsGetData, AdminStatsApiV1CommentAdminStatsGetErrors, AdminStatsApiV1CommentAdminStatsGetResponses, AuditCommentApiV1CommentAdminAuditPostData, AuditCommentApiV1CommentAdminAuditPostErrors, AuditCommentApiV1CommentAdminAuditPostResponses, AuditQueueApiV1CommentAdminAuditGetData, AuditQueueApiV1CommentAdminAuditGetErrors, AuditQueueApiV1CommentAdminAuditGetResponses, BulkAuditCommentApiV1CommentAdminAuditBatchPostData, BulkAuditCommentApiV1CommentAdminAuditBatchPostErrors, BulkAuditCommentApiV1CommentAdminAuditBatchPostResponses, CommentSourceApiV1CommentAdminSourceRpidGetData, CommentSourceApiV1CommentAdminSourceRpidGetErrors, CommentSourceApiV1CommentAdminSourceRpidGetResponses } from '../types.gen';

export class CommentAdminService {
    /**
     * 审核队列
     *
     * 审核队列。
     *
     * 可见范围按身份分层：
     *
     * - **root**：可查看全部状态的评论（默认全部，可用 `state` 收窄）；
     * - **被单独授权的管理员**：只允许查看 `auditing`（待审核），
     * 显式请求其他状态直接 403；评论正文（内容明文）对审核队列开放可见，
     * 但明文 IP 仍仅 root 可见。
     */
    public static auditQueueApiV1CommentAdminAuditGet<ThrowOnError extends boolean = false>(options?: Options<AuditQueueApiV1CommentAdminAuditGetData, ThrowOnError>): RequestResult<AuditQueueApiV1CommentAdminAuditGetResponses, AuditQueueApiV1CommentAdminAuditGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<AuditQueueApiV1CommentAdminAuditGetResponses, AuditQueueApiV1CommentAdminAuditGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/comment/admin/audit',
            ...options
        });
    }
    
    /**
     * 人工审核
     *
     * 对一条评论执行审核操作（通过 / 驳回 / 下架 / 恢复）。
     *
     * 仅 root 管理员可设置过审/没过审（含将已 normal 的评论重新审核），其余管理员无此权限。
     */
    public static auditCommentApiV1CommentAdminAuditPost<ThrowOnError extends boolean = false>(options: Options<AuditCommentApiV1CommentAdminAuditPostData, ThrowOnError>): RequestResult<AuditCommentApiV1CommentAdminAuditPostResponses, AuditCommentApiV1CommentAdminAuditPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<AuditCommentApiV1CommentAdminAuditPostResponses, AuditCommentApiV1CommentAdminAuditPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/comment/admin/audit',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 批量人工审核
     *
     * 对一批评论执行同一审核操作（通过 / 驳回 / 下架 / 恢复）。
     *
     * 仅 root 管理员可操作。内部逐条复用单条审核逻辑（含通知投递）。
     */
    public static bulkAuditCommentApiV1CommentAdminAuditBatchPost<ThrowOnError extends boolean = false>(options: Options<BulkAuditCommentApiV1CommentAdminAuditBatchPostData, ThrowOnError>): RequestResult<BulkAuditCommentApiV1CommentAdminAuditBatchPostResponses, BulkAuditCommentApiV1CommentAdminAuditBatchPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<BulkAuditCommentApiV1CommentAdminAuditBatchPostResponses, BulkAuditCommentApiV1CommentAdminAuditBatchPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/comment/admin/audit/batch',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 评论内容来源
     *
     * 按 rpid 返回该评论的内容来源（评论区归属、UP 主、可跳转地址）。
     *
     * 管理端「内容来源」链接点击时按需拉取；不含评论正文，任意管理员可见。
     */
    public static commentSourceApiV1CommentAdminSourceRpidGet<ThrowOnError extends boolean = false>(options: Options<CommentSourceApiV1CommentAdminSourceRpidGetData, ThrowOnError>): RequestResult<CommentSourceApiV1CommentAdminSourceRpidGetResponses, CommentSourceApiV1CommentAdminSourceRpidGetErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).get<CommentSourceApiV1CommentAdminSourceRpidGetResponses, CommentSourceApiV1CommentAdminSourceRpidGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/comment/admin/source/{rpid}',
            ...options
        });
    }
    
    /**
     * 查看原始IP（管理端）
     *
     * 查看一条评论的原始 IPv4 / IPv6（D3：仅管理端可见明文，root 专属）。
     */
    public static adminIpApiV1CommentAdminIpRpidGet<ThrowOnError extends boolean = false>(options: Options<AdminIpApiV1CommentAdminIpRpidGetData, ThrowOnError>): RequestResult<AdminIpApiV1CommentAdminIpRpidGetResponses, AdminIpApiV1CommentAdminIpRpidGetErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).get<AdminIpApiV1CommentAdminIpRpidGetResponses, AdminIpApiV1CommentAdminIpRpidGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/comment/admin/ip/{rpid}',
            ...options
        });
    }
    
    /**
     * 评论统计
     *
     * 评论区全局统计（管理端低频查询，管理员可见）。
     */
    public static adminStatsApiV1CommentAdminStatsGet<ThrowOnError extends boolean = false>(options?: Options<AdminStatsApiV1CommentAdminStatsGetData, ThrowOnError>): RequestResult<AdminStatsApiV1CommentAdminStatsGetResponses, AdminStatsApiV1CommentAdminStatsGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<AdminStatsApiV1CommentAdminStatsGetResponses, AdminStatsApiV1CommentAdminStatsGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/comment/admin/stats',
            ...options
        });
    }
}
