// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AggregateEventApiV1MessageEventAggregateGetData, AggregateEventApiV1MessageEventAggregateGetErrors, AggregateEventApiV1MessageEventAggregateGetResponses, DeleteEventApiV1MessageEventDeletePostData, DeleteEventApiV1MessageEventDeletePostErrors, DeleteEventApiV1MessageEventDeletePostResponses, ListEventApiV1MessageEventListGetData, ListEventApiV1MessageEventListGetErrors, ListEventApiV1MessageEventListGetResponses, ReadEventApiV1MessageEventReadPostData, ReadEventApiV1MessageEventReadPostErrors, ReadEventApiV1MessageEventReadPostResponses, ReportEventApiV1MessageEventReportPostData, ReportEventApiV1MessageEventReportPostErrors, ReportEventApiV1MessageEventReportPostResponses, UnreadEventApiV1MessageEventUnreadGetData, UnreadEventApiV1MessageEventUnreadGetErrors, UnreadEventApiV1MessageEventUnreadGetResponses } from '../types.gen';

export class MessageEventService {
    /**
     * 上报互动事件
     *
     * 上报一条点赞 / 回复 / @事件。
     *
     * 内部依次经过：消息设置闸门 → 自赞过滤 → `dedup_key` 幂等 → 落库。
     * 事件提醒是站内信，落库即送达（接收方经 /list / msg_feed 轮询读取），
     * 不再做任何第三方渠道推送或实时 / 批量分流。重复上报只会返回
     * `duplicated=True`，不会产生第二条提醒。
     *
     * 本接口面向内部服务调用（不要求登录态），mid 由请求体显式指定。
     */
    public static reportEventApiV1MessageEventReportPost<ThrowOnError extends boolean = false>(options: Options<ReportEventApiV1MessageEventReportPostData, ThrowOnError>): RequestResult<ReportEventApiV1MessageEventReportPostResponses, ReportEventApiV1MessageEventReportPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ReportEventApiV1MessageEventReportPostResponses, ReportEventApiV1MessageEventReportPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/event/report',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 聚合展示互动提醒
     *
     * 按来源实体聚合的提醒卡片列表（消息中心首页）。
     */
    public static aggregateEventApiV1MessageEventAggregateGet<ThrowOnError extends boolean = false>(options?: Options<AggregateEventApiV1MessageEventAggregateGetData, ThrowOnError>): RequestResult<AggregateEventApiV1MessageEventAggregateGetResponses, AggregateEventApiV1MessageEventAggregateGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<AggregateEventApiV1MessageEventAggregateGetResponses, AggregateEventApiV1MessageEventAggregateGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/event/aggregate',
            ...options
        });
    }
    
    /**
     * 互动提醒列表（B 站式聚合）
     *
     * 按内容聚合的互动提醒列表，对齐 B 站 x/msgfeed* 结构。
     *
     * - `data.latest`：最新一条聚合记录；
     * - `data.total.items`：本页聚合条目（每条含完整 users[] + item + counts）；
     * - `data.total.cursor`：翻页游标（is_end / id / time）。
     */
    public static listEventApiV1MessageEventListGet<ThrowOnError extends boolean = false>(options?: Options<ListEventApiV1MessageEventListGetData, ThrowOnError>): RequestResult<ListEventApiV1MessageEventListGetResponses, ListEventApiV1MessageEventListGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<ListEventApiV1MessageEventListGetResponses, ListEventApiV1MessageEventListGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/event/list',
            ...options
        });
    }
    
    /**
     * 标记互动提醒已读
     *
     * 标记已读：
     *
     * - 传 `event_ids` → 精确已读；
     * - 传 `event_type` → 该类型一键已读；
     * - 再加 `source_type + source_id` → 只清掉某一张聚合卡片。
     */
    public static readEventApiV1MessageEventReadPost<ThrowOnError extends boolean = false>(options: Options<ReadEventApiV1MessageEventReadPostData, ThrowOnError>): RequestResult<ReadEventApiV1MessageEventReadPostResponses, ReadEventApiV1MessageEventReadPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ReadEventApiV1MessageEventReadPostResponses, ReadEventApiV1MessageEventReadPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/event/read',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 删除互动提醒
     */
    public static deleteEventApiV1MessageEventDeletePost<ThrowOnError extends boolean = false>(options: Options<DeleteEventApiV1MessageEventDeletePostData, ThrowOnError>): RequestResult<DeleteEventApiV1MessageEventDeletePostResponses, DeleteEventApiV1MessageEventDeletePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<DeleteEventApiV1MessageEventDeletePostResponses, DeleteEventApiV1MessageEventDeletePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/event/delete',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 各类型互动未读数
     *
     * 一次查询返回 like / reply / at 的未读数，供前端渲染红点。
     */
    public static unreadEventApiV1MessageEventUnreadGet<ThrowOnError extends boolean = false>(options?: Options<UnreadEventApiV1MessageEventUnreadGetData, ThrowOnError>): RequestResult<UnreadEventApiV1MessageEventUnreadGetResponses, UnreadEventApiV1MessageEventUnreadGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<UnreadEventApiV1MessageEventUnreadGetResponses, UnreadEventApiV1MessageEventUnreadGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/event/unread',
            ...options
        });
    }
}
