// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AdminListNotifyApiV1MessageNotifyAdminListGetData, AdminListNotifyApiV1MessageNotifyAdminListGetErrors, AdminListNotifyApiV1MessageNotifyAdminListGetResponses, CreateNotifyApiV1MessageNotifyAdminCreatePostData, CreateNotifyApiV1MessageNotifyAdminCreatePostErrors, CreateNotifyApiV1MessageNotifyAdminCreatePostResponses, DeleteNotifyApiV1MessageNotifyDeletePostData, DeleteNotifyApiV1MessageNotifyDeletePostErrors, DeleteNotifyApiV1MessageNotifyDeletePostResponses, ListNotifyApiV1MessageNotifyListGetData, ListNotifyApiV1MessageNotifyListGetErrors, ListNotifyApiV1MessageNotifyListGetResponses, PullNotifyApiV1MessageNotifyPullGetData, PullNotifyApiV1MessageNotifyPullGetErrors, PullNotifyApiV1MessageNotifyPullGetResponses, RevokeNotifyApiV1MessageNotifyAdminRevokeNotifyIdPostData, RevokeNotifyApiV1MessageNotifyAdminRevokeNotifyIdPostErrors, RevokeNotifyApiV1MessageNotifyAdminRevokeNotifyIdPostResponses, SystemNotifyBiliApiV1MessageNotifySystemGetData, SystemNotifyBiliApiV1MessageNotifySystemGetErrors, SystemNotifyBiliApiV1MessageNotifySystemGetResponses, UnreadNotifyApiV1MessageNotifyUnreadGetData, UnreadNotifyApiV1MessageNotifyUnreadGetErrors, UnreadNotifyApiV1MessageNotifyUnreadGetResponses, UpdateNotifyApiV1MessageNotifyAdminUpdateNotifyIdPostData, UpdateNotifyApiV1MessageNotifyAdminUpdateNotifyIdPostErrors, UpdateNotifyApiV1MessageNotifyAdminUpdateNotifyIdPostResponses } from '../types.gen';

export class MessageNotifyService {
    /**
     * 定时拉取增量通知
     *
     * 拉取本用户可见的增量通知。
     *
     * 只返回 `id > cursor` 的通知，拉取后服务端会推进游标，
     * 因此**重复调用不会拿到重复数据**（即使客户端丢了本地游标）。
     * 每次拉取同时记一次用户活跃，用于后续推送策略分流。
     *
     * 本批通知在返回时即被自动标记为已读（读取即已读），响应的 `unread_count`
     * 是标记后的剩余未读数。
     */
    public static pullNotifyApiV1MessageNotifyPullGet<ThrowOnError extends boolean = false>(options?: Options<PullNotifyApiV1MessageNotifyPullGetData, ThrowOnError>): RequestResult<PullNotifyApiV1MessageNotifyPullGetResponses, PullNotifyApiV1MessageNotifyPullGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<PullNotifyApiV1MessageNotifyPullGetResponses, PullNotifyApiV1MessageNotifyPullGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/notify/pull',
            ...options
        });
    }
    
    /**
     * 分页查看历史通知
     *
     * 分页查看历史通知（不推进拉取游标），返回前本页通知自动置为已读。
     *
     * 出参 `is_read` 是本次读取前的快照，可据此高亮「本次新到」的通知。
     */
    public static listNotifyApiV1MessageNotifyListGet<ThrowOnError extends boolean = false>(options?: Options<ListNotifyApiV1MessageNotifyListGetData, ThrowOnError>): RequestResult<ListNotifyApiV1MessageNotifyListGetResponses, ListNotifyApiV1MessageNotifyListGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<ListNotifyApiV1MessageNotifyListGetResponses, ListNotifyApiV1MessageNotifyListGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/notify/list',
            ...options
        });
    }
    
    /**
     * 系统通知未读数
     */
    public static unreadNotifyApiV1MessageNotifyUnreadGet<ThrowOnError extends boolean = false>(options?: Options<UnreadNotifyApiV1MessageNotifyUnreadGetData, ThrowOnError>): RequestResult<UnreadNotifyApiV1MessageNotifyUnreadGetResponses, UnreadNotifyApiV1MessageNotifyUnreadGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<UnreadNotifyApiV1MessageNotifyUnreadGetResponses, UnreadNotifyApiV1MessageNotifyUnreadGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/notify/unread',
            ...options
        });
    }
    
    /**
     * 系统通知列表（模仿 B 站 feedsystem/system_notify/get）
     *
     * 模仿 B 站 `/x/v2/feedsystem/system_notify/get` 接口。
     *
     * 返回结构与 B 站保持一致：`code/msg/message/ttl` 外壳 + `data.system_notify_list`。
     * 列表项字段（`cursor` 纳秒时间戳、`content` 为 `{"web": "..."}` 的 JSON 字符串、
     * `type` 固定为 4、`is_send` 映射 `dispatched` 等）均与 B 站对齐。
     * 评论审核驳回等系统通知会以同样形态出现在该列表中。
     */
    public static systemNotifyBiliApiV1MessageNotifySystemGet<ThrowOnError extends boolean = false>(options?: Options<SystemNotifyBiliApiV1MessageNotifySystemGetData, ThrowOnError>): RequestResult<SystemNotifyBiliApiV1MessageNotifySystemGetResponses, SystemNotifyBiliApiV1MessageNotifySystemGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<SystemNotifyBiliApiV1MessageNotifySystemGetResponses, SystemNotifyBiliApiV1MessageNotifySystemGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/notify/system',
            ...options
        });
    }
    
    /**
     * 删除通知（仅管理员，逐用户软删）
     *
     * 仅管理员可调用。
     *
     * 普通用户不允许删除系统通知（系统通知面向全体、内容一致，用户只能标记已读）；
     * 删除需由管理员在管理界面操作。此处保留接口用于管理员按需清除指定用户的
     * 通知可见性（仅该用户不可见，不影响通知本体与其他用户）。
     */
    public static deleteNotifyApiV1MessageNotifyDeletePost<ThrowOnError extends boolean = false>(options: Options<DeleteNotifyApiV1MessageNotifyDeletePostData, ThrowOnError>): RequestResult<DeleteNotifyApiV1MessageNotifyDeletePostResponses, DeleteNotifyApiV1MessageNotifyDeletePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<DeleteNotifyApiV1MessageNotifyDeletePostResponses, DeleteNotifyApiV1MessageNotifyDeletePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/notify/delete',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 发布系统通知（管理员）
     *
     * 发布一条系统通知。
     *
     * `publish_now=False` 存为草稿；`publish_at` 为未来时间即定时发布，
     * 到点后由后台任务自动投递推送（活跃用户实时推、非活跃用户批量推）。
     *
     * 与对外 RPC `message.notify.rpc.publish_notify`（见 `app.mq.rpc_notify`）落到
     * 同一个执行体 `NotifyService.create`：HTTP 面向管理员浏览器侧、RPC 面向其它
     * 服务端系统，二者不再有各自的实现副本。差别仅在是否满足幂等——管理端是人工
     * 显式操作，不做 `(target_value, title)` 判重；RPC 走 `create_idempotent`，
     * 便于调用方超时重试而不重复打扰用户。
     */
    public static createNotifyApiV1MessageNotifyAdminCreatePost<ThrowOnError extends boolean = false>(options: Options<CreateNotifyApiV1MessageNotifyAdminCreatePostData, ThrowOnError>): RequestResult<CreateNotifyApiV1MessageNotifyAdminCreatePostResponses, CreateNotifyApiV1MessageNotifyAdminCreatePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<CreateNotifyApiV1MessageNotifyAdminCreatePostResponses, CreateNotifyApiV1MessageNotifyAdminCreatePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/notify/admin/create',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 修改系统通知（管理员）
     */
    public static updateNotifyApiV1MessageNotifyAdminUpdateNotifyIdPost<ThrowOnError extends boolean = false>(options: Options<UpdateNotifyApiV1MessageNotifyAdminUpdateNotifyIdPostData, ThrowOnError>): RequestResult<UpdateNotifyApiV1MessageNotifyAdminUpdateNotifyIdPostResponses, UpdateNotifyApiV1MessageNotifyAdminUpdateNotifyIdPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<UpdateNotifyApiV1MessageNotifyAdminUpdateNotifyIdPostResponses, UpdateNotifyApiV1MessageNotifyAdminUpdateNotifyIdPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/notify/admin/update/{notify_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 撤回系统通知（管理员）
     */
    public static revokeNotifyApiV1MessageNotifyAdminRevokeNotifyIdPost<ThrowOnError extends boolean = false>(options: Options<RevokeNotifyApiV1MessageNotifyAdminRevokeNotifyIdPostData, ThrowOnError>): RequestResult<RevokeNotifyApiV1MessageNotifyAdminRevokeNotifyIdPostResponses, RevokeNotifyApiV1MessageNotifyAdminRevokeNotifyIdPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<RevokeNotifyApiV1MessageNotifyAdminRevokeNotifyIdPostResponses, RevokeNotifyApiV1MessageNotifyAdminRevokeNotifyIdPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/notify/admin/revoke/{notify_id}',
            ...options
        });
    }
    
    /**
     * 通知列表（管理员）
     */
    public static adminListNotifyApiV1MessageNotifyAdminListGet<ThrowOnError extends boolean = false>(options?: Options<AdminListNotifyApiV1MessageNotifyAdminListGetData, ThrowOnError>): RequestResult<AdminListNotifyApiV1MessageNotifyAdminListGetResponses, AdminListNotifyApiV1MessageNotifyAdminListGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<AdminListNotifyApiV1MessageNotifyAdminListGetResponses, AdminListNotifyApiV1MessageNotifyAdminListGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/notify/admin/list',
            ...options
        });
    }
}
