// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { GetActivityApiV1MessageSettingActivityGetData, GetActivityApiV1MessageSettingActivityGetErrors, GetActivityApiV1MessageSettingActivityGetResponses, GetSettingApiV1MessageSettingGetData, GetSettingApiV1MessageSettingGetErrors, GetSettingApiV1MessageSettingGetResponses, UpdateSettingApiV1MessageSettingUpdatePostData, UpdateSettingApiV1MessageSettingUpdatePostErrors, UpdateSettingApiV1MessageSettingUpdatePostResponses } from '../types.gen';

export class MessageSettingService {
    /**
     * 获取消息设置
     *
     * 获取当前用户的消息设置，首次访问时按「全部开启」自动初始化。
     */
    public static getSettingApiV1MessageSettingGet<ThrowOnError extends boolean = false>(options?: Options<GetSettingApiV1MessageSettingGetData, ThrowOnError>): RequestResult<GetSettingApiV1MessageSettingGetResponses, GetSettingApiV1MessageSettingGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<GetSettingApiV1MessageSettingGetResponses, GetSettingApiV1MessageSettingGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/setting',
            ...options
        });
    }
    
    /**
     * 更新消息设置
     *
     * 部分更新：只写入本次显式传入的字段，未传字段保持原值。
     *
     * 关闭某类开关后，对应提醒会在**上报阶段就被短路**，不会落库也不会推送。
     */
    public static updateSettingApiV1MessageSettingUpdatePost<ThrowOnError extends boolean = false>(options: Options<UpdateSettingApiV1MessageSettingUpdatePostData, ThrowOnError>): RequestResult<UpdateSettingApiV1MessageSettingUpdatePostResponses, UpdateSettingApiV1MessageSettingUpdatePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<UpdateSettingApiV1MessageSettingUpdatePostResponses, UpdateSettingApiV1MessageSettingUpdatePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/setting/update',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 查看自身活跃度快照
     *
     * 活跃度快照：`is_active=True` 的用户走实时推送，否则进批量聚合推送。
     */
    public static getActivityApiV1MessageSettingActivityGet<ThrowOnError extends boolean = false>(options?: Options<GetActivityApiV1MessageSettingActivityGetData, ThrowOnError>): RequestResult<GetActivityApiV1MessageSettingActivityGetResponses, GetActivityApiV1MessageSettingActivityGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<GetActivityApiV1MessageSettingActivityGetResponses, GetActivityApiV1MessageSettingActivityGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/setting/activity',
            ...options
        });
    }
}
