// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AckSessionApiV1MessageDmAckPostData, AckSessionApiV1MessageDmAckPostErrors, AckSessionApiV1MessageDmAckPostResponses, DeleteMessagesApiV1MessageDmDeletePostData, DeleteMessagesApiV1MessageDmDeletePostErrors, DeleteMessagesApiV1MessageDmDeletePostResponses, DeleteSessionApiV1MessageDmSessionDeletePostData, DeleteSessionApiV1MessageDmSessionDeletePostErrors, DeleteSessionApiV1MessageDmSessionDeletePostResponses, ListMessagesApiV1MessageDmMessagesGetData, ListMessagesApiV1MessageDmMessagesGetErrors, ListMessagesApiV1MessageDmMessagesGetResponses, ListSessionsApiV1MessageDmSessionsGetData, ListSessionsApiV1MessageDmSessionsGetErrors, ListSessionsApiV1MessageDmSessionsGetResponses, RecallMessageApiV1MessageDmRecallPostData, RecallMessageApiV1MessageDmRecallPostErrors, RecallMessageApiV1MessageDmRecallPostResponses, SendDmApiV1MessageDmSendPostData, SendDmApiV1MessageDmSendPostErrors, SendDmApiV1MessageDmSendPostResponses, UnreadDmApiV1MessageDmUnreadGetData, UnreadDmApiV1MessageDmUnreadGetErrors, UnreadDmApiV1MessageDmUnreadGetResponses } from '../types.gen';

export class MessageDmService {
    /**
     * 发送私信
     *
     * 发送一条私信。
     *
     * 同步部分只写「双方索引行 + 双方会话行」，正文投递到 MQ 由消费者写入
     * msgkey 路由到的月度分库分表——发送接口的 RT 不受正文长度与建表 DDL 影响。
     * 响应里的 `content_async=False` 表示 MQ 不可用，已降级为同步落库。
     *
     * 若对方关闭了陌生人私信，返回 `filtered=True`：消息只保留在发送方视角。
     */
    public static sendDmApiV1MessageDmSendPost<ThrowOnError extends boolean = false>(options: Options<SendDmApiV1MessageDmSendPostData, ThrowOnError>): RequestResult<SendDmApiV1MessageDmSendPostResponses, SendDmApiV1MessageDmSendPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<SendDmApiV1MessageDmSendPostResponses, SendDmApiV1MessageDmSendPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/dm/send',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 会话列表
     */
    public static listSessionsApiV1MessageDmSessionsGet<ThrowOnError extends boolean = false>(options?: Options<ListSessionsApiV1MessageDmSessionsGetData, ThrowOnError>): RequestResult<ListSessionsApiV1MessageDmSessionsGetResponses, ListSessionsApiV1MessageDmSessionsGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<ListSessionsApiV1MessageDmSessionsGetResponses, ListSessionsApiV1MessageDmSessionsGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/dm/sessions',
            ...options
        });
    }
    
    /**
     * 删除会话
     */
    public static deleteSessionApiV1MessageDmSessionDeletePost<ThrowOnError extends boolean = false>(options: Options<DeleteSessionApiV1MessageDmSessionDeletePostData, ThrowOnError>): RequestResult<DeleteSessionApiV1MessageDmSessionDeletePostResponses, DeleteSessionApiV1MessageDmSessionDeletePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<DeleteSessionApiV1MessageDmSessionDeletePostResponses, DeleteSessionApiV1MessageDmSessionDeletePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/dm/session/delete',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 拉取聊天记录
     *
     * 按 msgkey 游标倒序翻页拉取聊天记录。
     *
     * 正文按 msgkey 批量回捞分片；若异步落库尚未完成，
     * 会回落到索引行冗余的摘要（`content_ready=False`），保证会话流始终可读。
     */
    public static listMessagesApiV1MessageDmMessagesGet<ThrowOnError extends boolean = false>(options: Options<ListMessagesApiV1MessageDmMessagesGetData, ThrowOnError>): RequestResult<ListMessagesApiV1MessageDmMessagesGetResponses, ListMessagesApiV1MessageDmMessagesGetErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).get<ListMessagesApiV1MessageDmMessagesGetResponses, ListMessagesApiV1MessageDmMessagesGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/dm/messages',
            ...options
        });
    }
    
    /**
     * 删除私信消息
     *
     * 删除消息：只影响自己视角，对方仍能看到。
     */
    public static deleteMessagesApiV1MessageDmDeletePost<ThrowOnError extends boolean = false>(options: Options<DeleteMessagesApiV1MessageDmDeletePostData, ThrowOnError>): RequestResult<DeleteMessagesApiV1MessageDmDeletePostResponses, DeleteMessagesApiV1MessageDmDeletePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<DeleteMessagesApiV1MessageDmDeletePostResponses, DeleteMessagesApiV1MessageDmDeletePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/dm/delete',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 撤回私信消息
     *
     * 撤回消息：双方均不可见，并物理清除分片中的正文。
     *
     * 仅发送者本人可撤回，且必须在配置的时间窗口内
     * （时间判定直接取 msgkey 内嵌的时间戳，无需回查数据库）。
     */
    public static recallMessageApiV1MessageDmRecallPost<ThrowOnError extends boolean = false>(options: Options<RecallMessageApiV1MessageDmRecallPostData, ThrowOnError>): RequestResult<RecallMessageApiV1MessageDmRecallPostResponses, RecallMessageApiV1MessageDmRecallPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<RecallMessageApiV1MessageDmRecallPostResponses, RecallMessageApiV1MessageDmRecallPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/dm/recall',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 标记会话已读
     */
    public static ackSessionApiV1MessageDmAckPost<ThrowOnError extends boolean = false>(options: Options<AckSessionApiV1MessageDmAckPostData, ThrowOnError>): RequestResult<AckSessionApiV1MessageDmAckPostResponses, AckSessionApiV1MessageDmAckPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<AckSessionApiV1MessageDmAckPostResponses, AckSessionApiV1MessageDmAckPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/dm/ack',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 私信未读总数
     */
    public static unreadDmApiV1MessageDmUnreadGet<ThrowOnError extends boolean = false>(options?: Options<UnreadDmApiV1MessageDmUnreadGetData, ThrowOnError>): RequestResult<UnreadDmApiV1MessageDmUnreadGetResponses, UnreadDmApiV1MessageDmUnreadGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<UnreadDmApiV1MessageDmUnreadGetResponses, UnreadDmApiV1MessageDmUnreadGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/dm/unread',
            ...options
        });
    }
}
