// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { TopicAuditApproveApiV1CommunityTopicAuditApprovePostData, TopicAuditApproveApiV1CommunityTopicAuditApprovePostErrors, TopicAuditApproveApiV1CommunityTopicAuditApprovePostResponses, TopicAuditListApiV1CommunityTopicAuditListGetData, TopicAuditListApiV1CommunityTopicAuditListGetErrors, TopicAuditListApiV1CommunityTopicAuditListGetResponses, TopicAuditRejectApiV1CommunityTopicAuditRejectPostData, TopicAuditRejectApiV1CommunityTopicAuditRejectPostErrors, TopicAuditRejectApiV1CommunityTopicAuditRejectPostResponses } from '../types.gen';

export class MomentTopicAuditService {
    /**
     * 管理员话题待审核列表
     */
    public static topicAuditListApiV1CommunityTopicAuditListGet<ThrowOnError extends boolean = false>(options?: Options<TopicAuditListApiV1CommunityTopicAuditListGetData, ThrowOnError>): RequestResult<TopicAuditListApiV1CommunityTopicAuditListGetResponses, TopicAuditListApiV1CommunityTopicAuditListGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<TopicAuditListApiV1CommunityTopicAuditListGetResponses, TopicAuditListApiV1CommunityTopicAuditListGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/topic/audit/list',
            ...options
        });
    }
    
    /**
     * 审核通过话题
     */
    public static topicAuditApproveApiV1CommunityTopicAuditApprovePost<ThrowOnError extends boolean = false>(options: Options<TopicAuditApproveApiV1CommunityTopicAuditApprovePostData, ThrowOnError>): RequestResult<TopicAuditApproveApiV1CommunityTopicAuditApprovePostResponses, TopicAuditApproveApiV1CommunityTopicAuditApprovePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<TopicAuditApproveApiV1CommunityTopicAuditApprovePostResponses, TopicAuditApproveApiV1CommunityTopicAuditApprovePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/topic/audit/approve',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 审核驳回话题
     */
    public static topicAuditRejectApiV1CommunityTopicAuditRejectPost<ThrowOnError extends boolean = false>(options: Options<TopicAuditRejectApiV1CommunityTopicAuditRejectPostData, ThrowOnError>): RequestResult<TopicAuditRejectApiV1CommunityTopicAuditRejectPostResponses, TopicAuditRejectApiV1CommunityTopicAuditRejectPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<TopicAuditRejectApiV1CommunityTopicAuditRejectPostResponses, TopicAuditRejectApiV1CommunityTopicAuditRejectPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/topic/audit/reject',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
