// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { DetailApiV1CommunityDetailMomentIdGetData, DetailApiV1CommunityDetailMomentIdGetErrors, DetailApiV1CommunityDetailMomentIdGetResponses, DetailsBatchApiV1CommunityDetailsPostData, DetailsBatchApiV1CommunityDetailsPostErrors, DetailsBatchApiV1CommunityDetailsPostResponses, FeedAllApiV1CommunityFeedAllGetData, FeedAllApiV1CommunityFeedAllGetErrors, FeedAllApiV1CommunityFeedAllGetResponses, FeedFollowingApiV1CommunityFeedFollowingGetData, FeedFollowingApiV1CommunityFeedFollowingGetErrors, FeedFollowingApiV1CommunityFeedFollowingGetResponses, FeedSpaceApiV1CommunityFeedSpaceMidGetData, FeedSpaceApiV1CommunityFeedSpaceMidGetErrors, FeedSpaceApiV1CommunityFeedSpaceMidGetResponses, GetMomentForwardsApiV1CommunityMomentIdForwardsGetData, GetMomentForwardsApiV1CommunityMomentIdForwardsGetErrors, GetMomentForwardsApiV1CommunityMomentIdForwardsGetResponses, GetMomentLikersApiV1CommunityMomentIdLikersGetData, GetMomentLikersApiV1CommunityMomentIdLikersGetErrors, GetMomentLikersApiV1CommunityMomentIdLikersGetResponses } from '../types.gen';

export class MomentFeedService {
    /**
     * 综合页 Feed
     */
    public static feedAllApiV1CommunityFeedAllGet<ThrowOnError extends boolean = false>(options?: Options<FeedAllApiV1CommunityFeedAllGetData, ThrowOnError>): RequestResult<FeedAllApiV1CommunityFeedAllGetResponses, FeedAllApiV1CommunityFeedAllGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<FeedAllApiV1CommunityFeedAllGetResponses, FeedAllApiV1CommunityFeedAllGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/feed/all',
            ...options
        });
    }
    
    /**
     * 关注流 Feed（我关注的人的动态）
     *
     * 关注流：仅展示当前登录用户**关注的人**发布的 normal 动态。
     *
     * 关注 mid 取自 ``msg_user_follow``（FollowService.list_following_mids），
     * 动态过滤与综合页一致（normal + 未软删 + pubTime 非空），按 pubTime 倒序。
     * 必须登录（RequiredUser），未登录直接 401。
     */
    public static feedFollowingApiV1CommunityFeedFollowingGet<ThrowOnError extends boolean = false>(options?: Options<FeedFollowingApiV1CommunityFeedFollowingGetData, ThrowOnError>): RequestResult<FeedFollowingApiV1CommunityFeedFollowingGetResponses, FeedFollowingApiV1CommunityFeedFollowingGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<FeedFollowingApiV1CommunityFeedFollowingGetResponses, FeedFollowingApiV1CommunityFeedFollowingGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/feed/following',
            ...options
        });
    }
    
    /**
     * 个人空间 Feed
     */
    public static feedSpaceApiV1CommunityFeedSpaceMidGet<ThrowOnError extends boolean = false>(options: Options<FeedSpaceApiV1CommunityFeedSpaceMidGetData, ThrowOnError>): RequestResult<FeedSpaceApiV1CommunityFeedSpaceMidGetResponses, FeedSpaceApiV1CommunityFeedSpaceMidGetErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).get<FeedSpaceApiV1CommunityFeedSpaceMidGetResponses, FeedSpaceApiV1CommunityFeedSpaceMidGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/feed/space/{mid}',
            ...options
        });
    }
    
    /**
     * 动态详情
     */
    public static detailApiV1CommunityDetailMomentIdGet<ThrowOnError extends boolean = false>(options: Options<DetailApiV1CommunityDetailMomentIdGetData, ThrowOnError>): RequestResult<DetailApiV1CommunityDetailMomentIdGetResponses, DetailApiV1CommunityDetailMomentIdGetErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).get<DetailApiV1CommunityDetailMomentIdGetResponses, DetailApiV1CommunityDetailMomentIdGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/detail/{moment_id}',
            ...options
        });
    }
    
    /**
     * 批量动态详情
     */
    public static detailsBatchApiV1CommunityDetailsPost<ThrowOnError extends boolean = false>(options: Options<DetailsBatchApiV1CommunityDetailsPostData, ThrowOnError>): RequestResult<DetailsBatchApiV1CommunityDetailsPostResponses, DetailsBatchApiV1CommunityDetailsPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<DetailsBatchApiV1CommunityDetailsPostResponses, DetailsBatchApiV1CommunityDetailsPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/details',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 点赞明细列表（公开可读）
     *
     * 该动态的点赞用户列表（按点赞时间倒序，分页）。
     *
     * 与 detail 接口一致：公开可读，匿名访客也能访问（与 P8-T7 一致的策略）。
     */
    public static getMomentLikersApiV1CommunityMomentIdLikersGet<ThrowOnError extends boolean = false>(options: Options<GetMomentLikersApiV1CommunityMomentIdLikersGetData, ThrowOnError>): RequestResult<GetMomentLikersApiV1CommunityMomentIdLikersGetResponses, GetMomentLikersApiV1CommunityMomentIdLikersGetErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).get<GetMomentLikersApiV1CommunityMomentIdLikersGetResponses, GetMomentLikersApiV1CommunityMomentIdLikersGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/{moment_id}/likers',
            ...options
        });
    }
    
    /**
     * 转发该动态的动态列表（公开可读）
     *
     * 转发该动态的 normal 动态列表（按 pubTime 倒序，分页）。
     *
     * 与 detail 接口一致：公开可读，匿名访客也能访问。
     */
    public static getMomentForwardsApiV1CommunityMomentIdForwardsGet<ThrowOnError extends boolean = false>(options: Options<GetMomentForwardsApiV1CommunityMomentIdForwardsGetData, ThrowOnError>): RequestResult<GetMomentForwardsApiV1CommunityMomentIdForwardsGetResponses, GetMomentForwardsApiV1CommunityMomentIdForwardsGetErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).get<GetMomentForwardsApiV1CommunityMomentIdForwardsGetResponses, GetMomentForwardsApiV1CommunityMomentIdForwardsGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/community/{moment_id}/forwards',
            ...options
        });
    }
}
