// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { PushMessageApiV1MessagePushPushPostData, PushMessageApiV1MessagePushPushPostErrors, PushMessageApiV1MessagePushPushPostResponses, SubmitFeedbackApiV1MessagePushFeedbackPostData, SubmitFeedbackApiV1MessagePushFeedbackPostErrors, SubmitFeedbackApiV1MessagePushFeedbackPostResponses, TestPushApiV1MessagePushTestPostData, TestPushApiV1MessagePushTestPostErrors, TestPushApiV1MessagePushTestPostResponses } from '../types.gen';

export class PushService {
    /**
     * 投递推送到队列
     *
     * 投递一条推送请求到 RabbitMQ，由 message-service 消费者异步分发。
     *
     * 等价于各微服务原先「直接调用 PushMe / PushPlus 接口」的逻辑，
     * 现在统一改为调用本接口，由 message-service 集中推送。
     * 上游透传的 x-bili-* 用户信息由 CurrentUser 依赖解析，
     * 在投递前直接拼进推送标题（标题前缀），便于消费者区分推送来源。
     *
     * 微服务间完全互信，不做令牌校验。
     */
    public static pushMessageApiV1MessagePushPushPost<ThrowOnError extends boolean = false>(options: Options<PushMessageApiV1MessagePushPushPostData, ThrowOnError>): RequestResult<PushMessageApiV1MessagePushPushPostResponses, PushMessageApiV1MessagePushPushPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<PushMessageApiV1MessagePushPushPostResponses, PushMessageApiV1MessagePushPushPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/push/push',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 立即发送测试推送
     *
     * 立即发送一条测试推送（不经过队列），便于前端 / 用户验证渠道配置。
     */
    public static testPushApiV1MessagePushTestPost<ThrowOnError extends boolean = false>(options: Options<TestPushApiV1MessagePushTestPostData, ThrowOnError>): RequestResult<TestPushApiV1MessagePushTestPostResponses, TestPushApiV1MessagePushTestPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<TestPushApiV1MessagePushTestPostResponses, TestPushApiV1MessagePushTestPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/push/test',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 提交用户反馈
     *
     * 前端提交反馈，仅推送到站长自己的推送设置（全局 message_config）。
     *
     * 不接收也不使用调用方传入的 per-user 渠道配置，固定回落到 message-service 的
     * 全局环境变量配置（MESSAGE_CONFIG），确保反馈只发到站长本人。
     * 标题包含来源（source）与用户标签，便于区分反馈来自哪个页面 / 哪位用户。
     *
     * 微服务间完全互信，不做令牌校验。
     */
    public static submitFeedbackApiV1MessagePushFeedbackPost<ThrowOnError extends boolean = false>(options: Options<SubmitFeedbackApiV1MessagePushFeedbackPostData, ThrowOnError>): RequestResult<SubmitFeedbackApiV1MessagePushFeedbackPostResponses, SubmitFeedbackApiV1MessagePushFeedbackPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<SubmitFeedbackApiV1MessagePushFeedbackPostResponses, SubmitFeedbackApiV1MessagePushFeedbackPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/push/feedback',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
