// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { AttachTagApiV1RpaTagAttachPostData, AttachTagApiV1RpaTagAttachPostErrors, AttachTagApiV1RpaTagAttachPostResponses, CreateTagApiV1RpaTagCreatePostData, CreateTagApiV1RpaTagCreatePostErrors, CreateTagApiV1RpaTagCreatePostResponses, DetachTagApiV1RpaTagDetachPostData, DetachTagApiV1RpaTagDetachPostErrors, DetachTagApiV1RpaTagDetachPostResponses, ListTagsApiV1RpaTagListPostData, ListTagsApiV1RpaTagListPostErrors, ListTagsApiV1RpaTagListPostResponses, ListTagsByTargetApiV1RpaTagListByTargetPostData, ListTagsByTargetApiV1RpaTagListByTargetPostErrors, ListTagsByTargetApiV1RpaTagListByTargetPostResponses } from '../types.gen';

export class RpaTagService {
    /**
     * 创建资源标签（进入待审核）
     */
    public static createTagApiV1RpaTagCreatePost<ThrowOnError extends boolean = false>(options: Options<CreateTagApiV1RpaTagCreatePostData, ThrowOnError>): RequestResult<CreateTagApiV1RpaTagCreatePostResponses, CreateTagApiV1RpaTagCreatePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<CreateTagApiV1RpaTagCreatePostResponses, CreateTagApiV1RpaTagCreatePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa_tag/create',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 为资源关联标签（仅可关联已审核通过标签）
     */
    public static attachTagApiV1RpaTagAttachPost<ThrowOnError extends boolean = false>(options: Options<AttachTagApiV1RpaTagAttachPostData, ThrowOnError>): RequestResult<AttachTagApiV1RpaTagAttachPostResponses, AttachTagApiV1RpaTagAttachPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<AttachTagApiV1RpaTagAttachPostResponses, AttachTagApiV1RpaTagAttachPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa_tag/attach',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 移除资源上的标签
     */
    public static detachTagApiV1RpaTagDetachPost<ThrowOnError extends boolean = false>(options: Options<DetachTagApiV1RpaTagDetachPostData, ThrowOnError>): RequestResult<DetachTagApiV1RpaTagDetachPostResponses, DetachTagApiV1RpaTagDetachPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<DetachTagApiV1RpaTagDetachPostResponses, DetachTagApiV1RpaTagDetachPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa_tag/detach',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 列出标签（普通用户仅 normal，root 可按状态筛选）
     */
    public static listTagsApiV1RpaTagListPost<ThrowOnError extends boolean = false>(options: Options<ListTagsApiV1RpaTagListPostData, ThrowOnError>): RequestResult<ListTagsApiV1RpaTagListPostResponses, ListTagsApiV1RpaTagListPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ListTagsApiV1RpaTagListPostResponses, ListTagsApiV1RpaTagListPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa_tag/list',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 查询某资源关联的标签（仅返回已审核通过）
     */
    public static listTagsByTargetApiV1RpaTagListByTargetPost<ThrowOnError extends boolean = false>(options: Options<ListTagsByTargetApiV1RpaTagListByTargetPostData, ThrowOnError>): RequestResult<ListTagsByTargetApiV1RpaTagListByTargetPostResponses, ListTagsByTargetApiV1RpaTagListByTargetPostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<ListTagsByTargetApiV1RpaTagListByTargetPostResponses, ListTagsByTargetApiV1RpaTagListByTargetPostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/rpa_tag/list-by-target',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
