// This file is auto-generated by @hey-api/openapi-ts

import type { RequestResult } from '../client';
import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { InvokeRpcApiV1MessageAdminRpcDebugInvokePostData, InvokeRpcApiV1MessageAdminRpcDebugInvokePostErrors, InvokeRpcApiV1MessageAdminRpcDebugInvokePostResponses, ListMethodsApiV1MessageAdminRpcDebugMethodsGetData, ListMethodsApiV1MessageAdminRpcDebugMethodsGetErrors, ListMethodsApiV1MessageAdminRpcDebugMethodsGetResponses } from '../types.gen';

export class RpcDebugService {
    /**
     * 列出可测试的 RPC 方法（契约登记表）
     *
     * 列出全部契约登记过的 RPC 方法（方法名 / 归属服务 / routing_key / 参数 Schema）。
     */
    public static listMethodsApiV1MessageAdminRpcDebugMethodsGet<ThrowOnError extends boolean = false>(options?: Options<ListMethodsApiV1MessageAdminRpcDebugMethodsGetData, ThrowOnError>): RequestResult<ListMethodsApiV1MessageAdminRpcDebugMethodsGetResponses, ListMethodsApiV1MessageAdminRpcDebugMethodsGetErrors, ThrowOnError, 'data'> {
        return (options?.client ?? client).get<ListMethodsApiV1MessageAdminRpcDebugMethodsGetResponses, ListMethodsApiV1MessageAdminRpcDebugMethodsGetErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/admin/rpc-debug/methods',
            ...options
        });
    }
    
    /**
     * 发起一次真实 RPC 往返（回显原始信封）
     *
     * 按契约方法发起真实 RPC，回显 `StandardResponse` 原始信封（失败也回显，不吞错）。
     *
     * - 未知方法 / 参数不合法：400 回包（错误详情在 msg 里），不投递消息；
     * - RPC 超时 / 未连接：500 回包（msg 带原因）。
     */
    public static invokeRpcApiV1MessageAdminRpcDebugInvokePost<ThrowOnError extends boolean = false>(options: Options<InvokeRpcApiV1MessageAdminRpcDebugInvokePostData, ThrowOnError>): RequestResult<InvokeRpcApiV1MessageAdminRpcDebugInvokePostResponses, InvokeRpcApiV1MessageAdminRpcDebugInvokePostErrors, ThrowOnError, 'data'> {
        return (options.client ?? client).post<InvokeRpcApiV1MessageAdminRpcDebugInvokePostResponses, InvokeRpcApiV1MessageAdminRpcDebugInvokePostErrors, ThrowOnError, 'data'>({
            responseStyle: 'data',
            url: '/api/v1/message/admin/rpc-debug/invoke',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
